/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game.impl;

import fr.n7.game.Chemin;
import fr.n7.game.Chemins;
import fr.n7.game.GamePackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chemins</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.game.impl.CheminsImpl#getListeChemins <em>Liste Chemins</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CheminsImpl extends territoireElementImpl implements Chemins
{
  /**
   * The cached value of the '{@link #getListeChemins() <em>Liste Chemins</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListeChemins()
   * @generated
   * @ordered
   */
  protected Chemin listeChemins;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CheminsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.CHEMINS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Chemin getListeChemins()
  {
    return listeChemins;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetListeChemins(Chemin newListeChemins, NotificationChain msgs)
  {
    Chemin oldListeChemins = listeChemins;
    listeChemins = newListeChemins;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.CHEMINS__LISTE_CHEMINS, oldListeChemins, newListeChemins);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setListeChemins(Chemin newListeChemins)
  {
    if (newListeChemins != listeChemins)
    {
      NotificationChain msgs = null;
      if (listeChemins != null)
        msgs = ((InternalEObject)listeChemins).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.CHEMINS__LISTE_CHEMINS, null, msgs);
      if (newListeChemins != null)
        msgs = ((InternalEObject)newListeChemins).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.CHEMINS__LISTE_CHEMINS, null, msgs);
      msgs = basicSetListeChemins(newListeChemins, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.CHEMINS__LISTE_CHEMINS, newListeChemins, newListeChemins));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.CHEMINS__LISTE_CHEMINS:
        return basicSetListeChemins(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.CHEMINS__LISTE_CHEMINS:
        return getListeChemins();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.CHEMINS__LISTE_CHEMINS:
        setListeChemins((Chemin)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.CHEMINS__LISTE_CHEMINS:
        setListeChemins((Chemin)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.CHEMINS__LISTE_CHEMINS:
        return listeChemins != null;
    }
    return super.eIsSet(featureID);
  }

} //CheminsImpl
