/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game.impl;

import fr.n7.game.Connaissance;
import fr.n7.game.Connaissances;
import fr.n7.game.GamePackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Connaissances</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.game.impl.ConnaissancesImpl#getListeConnaissance <em>Liste Connaissance</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConnaissancesImpl extends MinimalEObjectImpl.Container implements Connaissances
{
  /**
   * The cached value of the '{@link #getListeConnaissance() <em>Liste Connaissance</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getListeConnaissance()
   * @generated
   * @ordered
   */
  protected EList<Connaissance> listeConnaissance;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnaissancesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.CONNAISSANCES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Connaissance> getListeConnaissance()
  {
    if (listeConnaissance == null)
    {
      listeConnaissance = new EObjectContainmentEList<Connaissance>(Connaissance.class, this, GamePackage.CONNAISSANCES__LISTE_CONNAISSANCE);
    }
    return listeConnaissance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.CONNAISSANCES__LISTE_CONNAISSANCE:
        return ((InternalEList<?>)getListeConnaissance()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.CONNAISSANCES__LISTE_CONNAISSANCE:
        return getListeConnaissance();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.CONNAISSANCES__LISTE_CONNAISSANCE:
        getListeConnaissance().clear();
        getListeConnaissance().addAll((Collection<? extends Connaissance>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.CONNAISSANCES__LISTE_CONNAISSANCE:
        getListeConnaissance().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.CONNAISSANCES__LISTE_CONNAISSANCE:
        return listeConnaissance != null && !listeConnaissance.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ConnaissancesImpl
