/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game.impl;

import fr.n7.game.GamePackage;
import fr.n7.game.Interaction;
import fr.n7.game.Personne;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Personne</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.game.impl.PersonneImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.game.impl.PersonneImpl#isVisible <em>Visible</em>}</li>
 *   <li>{@link fr.n7.game.impl.PersonneImpl#isObligatoire <em>Obligatoire</em>}</li>
 *   <li>{@link fr.n7.game.impl.PersonneImpl#getPersonneElements <em>Personne Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PersonneImpl extends MinimalEObjectImpl.Container implements Personne
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isVisible() <em>Visible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isVisible()
   * @generated
   * @ordered
   */
  protected static final boolean VISIBLE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isVisible() <em>Visible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isVisible()
   * @generated
   * @ordered
   */
  protected boolean visible = VISIBLE_EDEFAULT;

  /**
   * The default value of the '{@link #isObligatoire() <em>Obligatoire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isObligatoire()
   * @generated
   * @ordered
   */
  protected static final boolean OBLIGATOIRE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isObligatoire() <em>Obligatoire</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isObligatoire()
   * @generated
   * @ordered
   */
  protected boolean obligatoire = OBLIGATOIRE_EDEFAULT;

  /**
   * The cached value of the '{@link #getPersonneElements() <em>Personne Elements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPersonneElements()
   * @generated
   * @ordered
   */
  protected Interaction personneElements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersonneImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.PERSONNE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.PERSONNE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isVisible()
  {
    return visible;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVisible(boolean newVisible)
  {
    boolean oldVisible = visible;
    visible = newVisible;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.PERSONNE__VISIBLE, oldVisible, visible));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isObligatoire()
  {
    return obligatoire;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setObligatoire(boolean newObligatoire)
  {
    boolean oldObligatoire = obligatoire;
    obligatoire = newObligatoire;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.PERSONNE__OBLIGATOIRE, oldObligatoire, obligatoire));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Interaction getPersonneElements()
  {
    return personneElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPersonneElements(Interaction newPersonneElements, NotificationChain msgs)
  {
    Interaction oldPersonneElements = personneElements;
    personneElements = newPersonneElements;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GamePackage.PERSONNE__PERSONNE_ELEMENTS, oldPersonneElements, newPersonneElements);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPersonneElements(Interaction newPersonneElements)
  {
    if (newPersonneElements != personneElements)
    {
      NotificationChain msgs = null;
      if (personneElements != null)
        msgs = ((InternalEObject)personneElements).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GamePackage.PERSONNE__PERSONNE_ELEMENTS, null, msgs);
      if (newPersonneElements != null)
        msgs = ((InternalEObject)newPersonneElements).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GamePackage.PERSONNE__PERSONNE_ELEMENTS, null, msgs);
      msgs = basicSetPersonneElements(newPersonneElements, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamePackage.PERSONNE__PERSONNE_ELEMENTS, newPersonneElements, newPersonneElements));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamePackage.PERSONNE__PERSONNE_ELEMENTS:
        return basicSetPersonneElements(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.PERSONNE__NAME:
        return getName();
      case GamePackage.PERSONNE__VISIBLE:
        return isVisible();
      case GamePackage.PERSONNE__OBLIGATOIRE:
        return isObligatoire();
      case GamePackage.PERSONNE__PERSONNE_ELEMENTS:
        return getPersonneElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.PERSONNE__NAME:
        setName((String)newValue);
        return;
      case GamePackage.PERSONNE__VISIBLE:
        setVisible((Boolean)newValue);
        return;
      case GamePackage.PERSONNE__OBLIGATOIRE:
        setObligatoire((Boolean)newValue);
        return;
      case GamePackage.PERSONNE__PERSONNE_ELEMENTS:
        setPersonneElements((Interaction)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.PERSONNE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GamePackage.PERSONNE__VISIBLE:
        setVisible(VISIBLE_EDEFAULT);
        return;
      case GamePackage.PERSONNE__OBLIGATOIRE:
        setObligatoire(OBLIGATOIRE_EDEFAULT);
        return;
      case GamePackage.PERSONNE__PERSONNE_ELEMENTS:
        setPersonneElements((Interaction)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.PERSONNE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GamePackage.PERSONNE__VISIBLE:
        return visible != VISIBLE_EDEFAULT;
      case GamePackage.PERSONNE__OBLIGATOIRE:
        return obligatoire != OBLIGATOIRE_EDEFAULT;
      case GamePackage.PERSONNE__PERSONNE_ELEMENTS:
        return personneElements != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", visible: ");
    result.append(visible);
    result.append(", obligatoire: ");
    result.append(obligatoire);
    result.append(')');
    return result.toString();
  }

} //PersonneImpl
