/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.game.Action#getConditionAction <em>Condition Action</em>}</li>
 *   <li>{@link fr.n7.game.Action#getListeChoix <em>Liste Choix</em>}</li>
 *   <li>{@link fr.n7.game.Action#getListeConnaissances <em>Liste Connaissances</em>}</li>
 *   <li>{@link fr.n7.game.Action#getListeObjets <em>Liste Objets</em>}</li>
 *   <li>{@link fr.n7.game.Action#getAttributionConnaissance <em>Attribution Connaissance</em>}</li>
 *   <li>{@link fr.n7.game.Action#getAttributionObjet <em>Attribution Objet</em>}</li>
 *   <li>{@link fr.n7.game.Action#getListeObjetsConsommes <em>Liste Objets Consommes</em>}</li>
 *   <li>{@link fr.n7.game.Action#getConsommationObjet <em>Consommation Objet</em>}</li>
 * </ul>
 *
 * @see fr.n7.game.GamePackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Action</em>' containment reference.
   * @see #setConditionAction(Condition)
   * @see fr.n7.game.GamePackage#getAction_ConditionAction()
   * @model containment="true"
   * @generated
   */
  Condition getConditionAction();

  /**
   * Sets the value of the '{@link fr.n7.game.Action#getConditionAction <em>Condition Action</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition Action</em>' containment reference.
   * @see #getConditionAction()
   * @generated
   */
  void setConditionAction(Condition value);

  /**
   * Returns the value of the '<em><b>Liste Choix</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.game.Choix}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Liste Choix</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getAction_ListeChoix()
   * @model containment="true"
   * @generated
   */
  EList<Choix> getListeChoix();

  /**
   * Returns the value of the '<em><b>Liste Connaissances</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.game.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Liste Connaissances</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getAction_ListeConnaissances()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getListeConnaissances();

  /**
   * Returns the value of the '<em><b>Liste Objets</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.game.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Liste Objets</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getAction_ListeObjets()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getListeObjets();

  /**
   * Returns the value of the '<em><b>Attribution Connaissance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribution Connaissance</em>' containment reference.
   * @see #setAttributionConnaissance(Condition)
   * @see fr.n7.game.GamePackage#getAction_AttributionConnaissance()
   * @model containment="true"
   * @generated
   */
  Condition getAttributionConnaissance();

  /**
   * Sets the value of the '{@link fr.n7.game.Action#getAttributionConnaissance <em>Attribution Connaissance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribution Connaissance</em>' containment reference.
   * @see #getAttributionConnaissance()
   * @generated
   */
  void setAttributionConnaissance(Condition value);

  /**
   * Returns the value of the '<em><b>Attribution Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribution Objet</em>' containment reference.
   * @see #setAttributionObjet(Condition)
   * @see fr.n7.game.GamePackage#getAction_AttributionObjet()
   * @model containment="true"
   * @generated
   */
  Condition getAttributionObjet();

  /**
   * Sets the value of the '{@link fr.n7.game.Action#getAttributionObjet <em>Attribution Objet</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribution Objet</em>' containment reference.
   * @see #getAttributionObjet()
   * @generated
   */
  void setAttributionObjet(Condition value);

  /**
   * Returns the value of the '<em><b>Liste Objets Consommes</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.game.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Liste Objets Consommes</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getAction_ListeObjetsConsommes()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getListeObjetsConsommes();

  /**
   * Returns the value of the '<em><b>Consommation Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Consommation Objet</em>' containment reference.
   * @see #setConsommationObjet(Condition)
   * @see fr.n7.game.GamePackage#getAction_ConsommationObjet()
   * @model containment="true"
   * @generated
   */
  Condition getConsommationObjet();

  /**
   * Sets the value of the '{@link fr.n7.game.Action#getConsommationObjet <em>Consommation Objet</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Consommation Objet</em>' containment reference.
   * @see #getConsommationObjet()
   * @generated
   */
  void setConsommationObjet(Condition value);

} // Action
