/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connaissances</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.game.Connaissances#getListeConnaissances <em>Liste Connaissances</em>}</li>
 * </ul>
 *
 * @see fr.n7.game.GamePackage#getConnaissances()
 * @model
 * @generated
 */
public interface Connaissances extends EObject
{
  /**
   * Returns the value of the '<em><b>Liste Connaissances</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.game.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Liste Connaissances</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getConnaissances_ListeConnaissances()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getListeConnaissances();

} // Connaissances
