/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Explorateur</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.game.Explorateur#getExplorateurElements <em>Explorateur Elements</em>}</li>
 * </ul>
 *
 * @see fr.n7.game.GamePackage#getExplorateur()
 * @model
 * @generated
 */
public interface Explorateur extends territoireElement
{
  /**
   * Returns the value of the '<em><b>Explorateur Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Explorateur Elements</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getExplorateur_ExplorateurElements()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getExplorateurElements();

} // Explorateur
