/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.game.GameFactory
 * @model kind="package"
 * @generated
 */
public interface GamePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "game";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/Game";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "game";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GamePackage eINSTANCE = fr.n7.game.impl.GamePackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.game.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.GameImpl
   * @see fr.n7.game.impl.GamePackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Territoire Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__TERRITOIRE_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.territoireElementImpl <em>territoire Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.territoireElementImpl
   * @see fr.n7.game.impl.GamePackageImpl#getterritoireElement()
   * @generated
   */
  int TERRITOIRE_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>territoire Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERRITOIRE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ExplorateurImpl <em>Explorateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ExplorateurImpl
   * @see fr.n7.game.impl.GamePackageImpl#getExplorateur()
   * @generated
   */
  int EXPLORATEUR = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__NAME = TERRITOIRE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Sac</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__SAC = TERRITOIRE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Connaissances</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__CONNAISSANCES = TERRITOIRE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Position</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__POSITION = TERRITOIRE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Explorateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR_FEATURE_COUNT = TERRITOIRE_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.SacImpl <em>Sac</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.SacImpl
   * @see fr.n7.game.impl.GamePackageImpl#getSac()
   * @generated
   */
  int SAC = 3;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAC__TAILLE = 0;

  /**
   * The feature id for the '<em><b>Sac Elements</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAC__SAC_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Sac</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.LieuImpl <em>Lieu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.LieuImpl
   * @see fr.n7.game.impl.GamePackageImpl#getLieu()
   * @generated
   */
  int LIEU = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__TYPE = TERRITOIRE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__NAME = TERRITOIRE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__DESCRIPTION = TERRITOIRE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__CONDITION_DESCRIPTION = TERRITOIRE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Personnes</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__PERSONNES = TERRITOIRE_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Connaissances</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__CONNAISSANCES = TERRITOIRE_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Objets</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__OBJETS = TERRITOIRE_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Depot Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__DEPOT_OBJET = TERRITOIRE_ELEMENT_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Liste Chemins</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__LISTE_CHEMINS = TERRITOIRE_ELEMENT_FEATURE_COUNT + 8;

  /**
   * The number of structural features of the '<em>Lieu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FEATURE_COUNT = TERRITOIRE_ELEMENT_FEATURE_COUNT + 9;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.PersonnesImpl <em>Personnes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.PersonnesImpl
   * @see fr.n7.game.impl.GamePackageImpl#getPersonnes()
   * @generated
   */
  int PERSONNES = 5;

  /**
   * The feature id for the '<em><b>Liste Personnes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNES__LISTE_PERSONNES = TERRITOIRE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Personnes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNES_FEATURE_COUNT = TERRITOIRE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.PersonneImpl <em>Personne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.PersonneImpl
   * @see fr.n7.game.impl.GamePackageImpl#getPersonne()
   * @generated
   */
  int PERSONNE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__NAME = 0;

  /**
   * The feature id for the '<em><b>Visible</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__VISIBLE = 1;

  /**
   * The feature id for the '<em><b>Obligatoire</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__OBLIGATOIRE = 2;

  /**
   * The feature id for the '<em><b>Personne Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__PERSONNE_ELEMENTS = 3;

  /**
   * The number of structural features of the '<em>Personne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.InteractionImpl <em>Interaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.InteractionImpl
   * @see fr.n7.game.impl.GamePackageImpl#getInteraction()
   * @generated
   */
  int INTERACTION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__TEXTE = 1;

  /**
   * The feature id for the '<em><b>Interaction Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__INTERACTION_ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>Interaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ChoixImpl <em>Choix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ChoixImpl
   * @see fr.n7.game.impl.GamePackageImpl#getChoix()
   * @generated
   */
  int CHOIX = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__NAME = 0;

  /**
   * The feature id for the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__TEXTE = 1;

  /**
   * The feature id for the '<em><b>Liste Actions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__LISTE_ACTIONS = 2;

  /**
   * The feature id for the '<em><b>Choixdebut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CHOIXDEBUT = 3;

  /**
   * The feature id for the '<em><b>Conditon Choix Debut</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CONDITON_CHOIX_DEBUT = 4;

  /**
   * The feature id for the '<em><b>Choixfin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CHOIXFIN = 5;

  /**
   * The feature id for the '<em><b>Condition Choix Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CONDITION_CHOIX_FIN = 6;

  /**
   * The number of structural features of the '<em>Choix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ActionImpl
   * @see fr.n7.game.impl.GamePackageImpl#getAction()
   * @generated
   */
  int ACTION = 9;

  /**
   * The feature id for the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__TEXTE = 0;

  /**
   * The feature id for the '<em><b>Condition Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CONDITION_ACTION = 1;

  /**
   * The feature id for the '<em><b>Liste Choix</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_CHOIX = 2;

  /**
   * The feature id for the '<em><b>Liste Connaissances</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_CONNAISSANCES = 3;

  /**
   * The feature id for the '<em><b>Liste Objets</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_OBJETS = 4;

  /**
   * The feature id for the '<em><b>Attribution Connaissance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ATTRIBUTION_CONNAISSANCE = 5;

  /**
   * The feature id for the '<em><b>Attribution Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ATTRIBUTION_OBJET = 6;

  /**
   * The feature id for the '<em><b>Liste Objets Consommes</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_OBJETS_CONSOMMES = 7;

  /**
   * The feature id for the '<em><b>Liste Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_QUANTITE = 8;

  /**
   * The feature id for the '<em><b>Consommation Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CONSOMMATION_OBJET = 9;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 10;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ObjetExplorateurImpl <em>Objet Explorateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ObjetExplorateurImpl
   * @see fr.n7.game.impl.GamePackageImpl#getObjetExplorateur()
   * @generated
   */
  int OBJET_EXPLORATEUR = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_EXPLORATEUR__NAME = 0;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_EXPLORATEUR__TAILLE = 1;

  /**
   * The feature id for the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_EXPLORATEUR__QUANTITE = 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_EXPLORATEUR__DESCRIPTION = 3;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_EXPLORATEUR__CONDITION_DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Transformable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_EXPLORATEUR__TRANSFORMABLE = 5;

  /**
   * The number of structural features of the '<em>Objet Explorateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_EXPLORATEUR_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ObjetLieuImpl <em>Objet Lieu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ObjetLieuImpl
   * @see fr.n7.game.impl.GamePackageImpl#getObjetLieu()
   * @generated
   */
  int OBJET_LIEU = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU__NAME = 0;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU__TAILLE = 1;

  /**
   * The feature id for the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU__QUANTITE = 2;

  /**
   * The feature id for the '<em><b>Condition Transmission</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU__CONDITION_TRANSMISSION = 3;

  /**
   * The feature id for the '<em><b>Condition Consommation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU__CONDITION_CONSOMMATION = 4;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU__DESCRIPTION = 5;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU__CONDITION_DESCRIPTION = 6;

  /**
   * The feature id for the '<em><b>Transformable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU__TRANSFORMABLE = 7;

  /**
   * The number of structural features of the '<em>Objet Lieu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_LIEU_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ObjetsExplorateurImpl <em>Objets Explorateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ObjetsExplorateurImpl
   * @see fr.n7.game.impl.GamePackageImpl#getObjetsExplorateur()
   * @generated
   */
  int OBJETS_EXPLORATEUR = 12;

  /**
   * The feature id for the '<em><b>Liste Objets</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJETS_EXPLORATEUR__LISTE_OBJETS = TERRITOIRE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Objets Explorateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJETS_EXPLORATEUR_FEATURE_COUNT = TERRITOIRE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ObjetsLieuImpl <em>Objets Lieu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ObjetsLieuImpl
   * @see fr.n7.game.impl.GamePackageImpl#getObjetsLieu()
   * @generated
   */
  int OBJETS_LIEU = 13;

  /**
   * The feature id for the '<em><b>Liste Objets</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJETS_LIEU__LISTE_OBJETS = TERRITOIRE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Objets Lieu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJETS_LIEU_FEATURE_COUNT = TERRITOIRE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ConnaissancesImpl <em>Connaissances</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ConnaissancesImpl
   * @see fr.n7.game.impl.GamePackageImpl#getConnaissances()
   * @generated
   */
  int CONNAISSANCES = 14;

  /**
   * The feature id for the '<em><b>Liste Connaissances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCES__LISTE_CONNAISSANCES = TERRITOIRE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Connaissances</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCES_FEATURE_COUNT = TERRITOIRE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ConnaissanceImpl
   * @see fr.n7.game.impl.GamePackageImpl#getConnaissance()
   * @generated
   */
  int CONNAISSANCE = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Condition Connaissance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__CONDITION_CONNAISSANCE = 2;

  /**
   * The number of structural features of the '<em>Connaissance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ConditionsImpl <em>Conditions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ConditionsImpl
   * @see fr.n7.game.impl.GamePackageImpl#getConditions()
   * @generated
   */
  int CONDITIONS = 16;

  /**
   * The feature id for the '<em><b>Liste Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONS__LISTE_CONDITIONS = TERRITOIRE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Conditions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONS_FEATURE_COUNT = TERRITOIRE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ConditionImpl
   * @see fr.n7.game.impl.GamePackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION = 1;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.CheminsImpl <em>Chemins</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.CheminsImpl
   * @see fr.n7.game.impl.GamePackageImpl#getChemins()
   * @generated
   */
  int CHEMINS = 18;

  /**
   * The feature id for the '<em><b>Liste Chemins</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMINS__LISTE_CHEMINS = TERRITOIRE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Chemins</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMINS_FEATURE_COUNT = TERRITOIRE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.CheminImpl <em>Chemin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.CheminImpl
   * @see fr.n7.game.impl.GamePackageImpl#getChemin()
   * @generated
   */
  int CHEMIN = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__CONDITION_DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__SOURCE = 3;

  /**
   * The feature id for the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DESTINATION = 4;

  /**
   * The feature id for the '<em><b>Obligatoire</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__OBLIGATOIRE = 5;

  /**
   * The feature id for the '<em><b>Visible</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__VISIBLE = 6;

  /**
   * The feature id for the '<em><b>Ouvert</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__OUVERT = 7;

  /**
   * The feature id for the '<em><b>Liste Connaissances</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__LISTE_CONNAISSANCES = 8;

  /**
   * The feature id for the '<em><b>Liste Objets</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__LISTE_OBJETS = 9;

  /**
   * The feature id for the '<em><b>Liste Objets Consommes</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__LISTE_OBJETS_CONSOMMES = 10;

  /**
   * The number of structural features of the '<em>Chemin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link fr.n7.game.TypeLieu <em>Type Lieu</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.TypeLieu
   * @see fr.n7.game.impl.GamePackageImpl#getTypeLieu()
   * @generated
   */
  int TYPE_LIEU = 20;


  /**
   * Returns the meta object for class '{@link fr.n7.game.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see fr.n7.game.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Game#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Game#getName()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Game#getTerritoireElements <em>Territoire Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Territoire Elements</em>'.
   * @see fr.n7.game.Game#getTerritoireElements()
   * @see #getGame()
   * @generated
   */
  EReference getGame_TerritoireElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.territoireElement <em>territoire Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>territoire Element</em>'.
   * @see fr.n7.game.territoireElement
   * @generated
   */
  EClass getterritoireElement();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Explorateur <em>Explorateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Explorateur</em>'.
   * @see fr.n7.game.Explorateur
   * @generated
   */
  EClass getExplorateur();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Explorateur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Explorateur#getName()
   * @see #getExplorateur()
   * @generated
   */
  EAttribute getExplorateur_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Explorateur#getSac <em>Sac</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sac</em>'.
   * @see fr.n7.game.Explorateur#getSac()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Sac();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Explorateur#getConnaissances <em>Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Connaissances</em>'.
   * @see fr.n7.game.Explorateur#getConnaissances()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Connaissances();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Explorateur#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Position</em>'.
   * @see fr.n7.game.Explorateur#getPosition()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_Position();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Sac <em>Sac</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sac</em>'.
   * @see fr.n7.game.Sac
   * @generated
   */
  EClass getSac();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Sac#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see fr.n7.game.Sac#getTaille()
   * @see #getSac()
   * @generated
   */
  EAttribute getSac_Taille();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Sac#getSacElements <em>Sac Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sac Elements</em>'.
   * @see fr.n7.game.Sac#getSacElements()
   * @see #getSac()
   * @generated
   */
  EReference getSac_SacElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Lieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lieu</em>'.
   * @see fr.n7.game.Lieu
   * @generated
   */
  EClass getLieu();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Lieu#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see fr.n7.game.Lieu#getType()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Type();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Lieu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Lieu#getName()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Lieu#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.Lieu#getDescription()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Lieu#getConditionDescription <em>Condition Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Description</em>'.
   * @see fr.n7.game.Lieu#getConditionDescription()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_ConditionDescription();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Lieu#getPersonnes <em>Personnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Personnes</em>'.
   * @see fr.n7.game.Lieu#getPersonnes()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Personnes();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Lieu#getConnaissances <em>Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Connaissances</em>'.
   * @see fr.n7.game.Lieu#getConnaissances()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Connaissances();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Lieu#getObjets <em>Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Objets</em>'.
   * @see fr.n7.game.Lieu#getObjets()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_Objets();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Lieu#getDepotObjet <em>Depot Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Depot Objet</em>'.
   * @see fr.n7.game.Lieu#getDepotObjet()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_DepotObjet();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Lieu#getListeChemins <em>Liste Chemins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Liste Chemins</em>'.
   * @see fr.n7.game.Lieu#getListeChemins()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_ListeChemins();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Personnes <em>Personnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Personnes</em>'.
   * @see fr.n7.game.Personnes
   * @generated
   */
  EClass getPersonnes();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Personnes#getListePersonnes <em>Liste Personnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Liste Personnes</em>'.
   * @see fr.n7.game.Personnes#getListePersonnes()
   * @see #getPersonnes()
   * @generated
   */
  EReference getPersonnes_ListePersonnes();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Personne <em>Personne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Personne</em>'.
   * @see fr.n7.game.Personne
   * @generated
   */
  EClass getPersonne();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Personne#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Personne#getName()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Name();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Personne#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Visible</em>'.
   * @see fr.n7.game.Personne#getVisible()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_Visible();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Personne#getObligatoire <em>Obligatoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Obligatoire</em>'.
   * @see fr.n7.game.Personne#getObligatoire()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_Obligatoire();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Personne#getPersonneElements <em>Personne Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Personne Elements</em>'.
   * @see fr.n7.game.Personne#getPersonneElements()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_PersonneElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Interaction <em>Interaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interaction</em>'.
   * @see fr.n7.game.Interaction
   * @generated
   */
  EClass getInteraction();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Interaction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Interaction#getName()
   * @see #getInteraction()
   * @generated
   */
  EAttribute getInteraction_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Interaction#getTexte <em>Texte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texte</em>'.
   * @see fr.n7.game.Interaction#getTexte()
   * @see #getInteraction()
   * @generated
   */
  EAttribute getInteraction_Texte();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Interaction#getInteractionElements <em>Interaction Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Interaction Elements</em>'.
   * @see fr.n7.game.Interaction#getInteractionElements()
   * @see #getInteraction()
   * @generated
   */
  EReference getInteraction_InteractionElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Choix <em>Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choix</em>'.
   * @see fr.n7.game.Choix
   * @generated
   */
  EClass getChoix();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Choix#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Choix#getName()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Choix#getTexte <em>Texte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texte</em>'.
   * @see fr.n7.game.Choix#getTexte()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Texte();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Choix#getListeActions <em>Liste Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Liste Actions</em>'.
   * @see fr.n7.game.Choix#getListeActions()
   * @see #getChoix()
   * @generated
   */
  EReference getChoix_ListeActions();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Choix#getChoixdebut <em>Choixdebut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Choixdebut</em>'.
   * @see fr.n7.game.Choix#getChoixdebut()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Choixdebut();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Choix#getConditonChoixDebut <em>Conditon Choix Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditon Choix Debut</em>'.
   * @see fr.n7.game.Choix#getConditonChoixDebut()
   * @see #getChoix()
   * @generated
   */
  EReference getChoix_ConditonChoixDebut();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Choix#getChoixfin <em>Choixfin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Choixfin</em>'.
   * @see fr.n7.game.Choix#getChoixfin()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Choixfin();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Choix#getConditionChoixFin <em>Condition Choix Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Choix Fin</em>'.
   * @see fr.n7.game.Choix#getConditionChoixFin()
   * @see #getChoix()
   * @generated
   */
  EReference getChoix_ConditionChoixFin();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see fr.n7.game.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Action#getTexte <em>Texte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texte</em>'.
   * @see fr.n7.game.Action#getTexte()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Texte();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Action#getConditionAction <em>Condition Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Action</em>'.
   * @see fr.n7.game.Action#getConditionAction()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ConditionAction();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Action#getListeChoix <em>Liste Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Liste Choix</em>'.
   * @see fr.n7.game.Action#getListeChoix()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ListeChoix();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Action#getListeConnaissances <em>Liste Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Liste Connaissances</em>'.
   * @see fr.n7.game.Action#getListeConnaissances()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ListeConnaissances();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Action#getListeObjets <em>Liste Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Liste Objets</em>'.
   * @see fr.n7.game.Action#getListeObjets()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ListeObjets();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Action#getAttributionConnaissance <em>Attribution Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribution Connaissance</em>'.
   * @see fr.n7.game.Action#getAttributionConnaissance()
   * @see #getAction()
   * @generated
   */
  EReference getAction_AttributionConnaissance();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Action#getAttributionObjet <em>Attribution Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribution Objet</em>'.
   * @see fr.n7.game.Action#getAttributionObjet()
   * @see #getAction()
   * @generated
   */
  EReference getAction_AttributionObjet();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Action#getListeObjetsConsommes <em>Liste Objets Consommes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Liste Objets Consommes</em>'.
   * @see fr.n7.game.Action#getListeObjetsConsommes()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ListeObjetsConsommes();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Action#getListeQuantite <em>Liste Quantite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Liste Quantite</em>'.
   * @see fr.n7.game.Action#getListeQuantite()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_ListeQuantite();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Action#getConsommationObjet <em>Consommation Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Consommation Objet</em>'.
   * @see fr.n7.game.Action#getConsommationObjet()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ConsommationObjet();

  /**
   * Returns the meta object for class '{@link fr.n7.game.ObjetExplorateur <em>Objet Explorateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objet Explorateur</em>'.
   * @see fr.n7.game.ObjetExplorateur
   * @generated
   */
  EClass getObjetExplorateur();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.ObjetExplorateur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.ObjetExplorateur#getName()
   * @see #getObjetExplorateur()
   * @generated
   */
  EAttribute getObjetExplorateur_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.ObjetExplorateur#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see fr.n7.game.ObjetExplorateur#getTaille()
   * @see #getObjetExplorateur()
   * @generated
   */
  EAttribute getObjetExplorateur_Taille();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.ObjetExplorateur#getQuantite <em>Quantite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantite</em>'.
   * @see fr.n7.game.ObjetExplorateur#getQuantite()
   * @see #getObjetExplorateur()
   * @generated
   */
  EAttribute getObjetExplorateur_Quantite();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.ObjetExplorateur#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.ObjetExplorateur#getDescription()
   * @see #getObjetExplorateur()
   * @generated
   */
  EAttribute getObjetExplorateur_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.ObjetExplorateur#getConditionDescription <em>Condition Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Description</em>'.
   * @see fr.n7.game.ObjetExplorateur#getConditionDescription()
   * @see #getObjetExplorateur()
   * @generated
   */
  EReference getObjetExplorateur_ConditionDescription();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.ObjetExplorateur#getTransformable <em>Transformable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transformable</em>'.
   * @see fr.n7.game.ObjetExplorateur#getTransformable()
   * @see #getObjetExplorateur()
   * @generated
   */
  EReference getObjetExplorateur_Transformable();

  /**
   * Returns the meta object for class '{@link fr.n7.game.ObjetLieu <em>Objet Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objet Lieu</em>'.
   * @see fr.n7.game.ObjetLieu
   * @generated
   */
  EClass getObjetLieu();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.ObjetLieu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.ObjetLieu#getName()
   * @see #getObjetLieu()
   * @generated
   */
  EAttribute getObjetLieu_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.ObjetLieu#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see fr.n7.game.ObjetLieu#getTaille()
   * @see #getObjetLieu()
   * @generated
   */
  EAttribute getObjetLieu_Taille();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.ObjetLieu#getQuantite <em>Quantite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantite</em>'.
   * @see fr.n7.game.ObjetLieu#getQuantite()
   * @see #getObjetLieu()
   * @generated
   */
  EAttribute getObjetLieu_Quantite();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.ObjetLieu#getConditionTransmission <em>Condition Transmission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Transmission</em>'.
   * @see fr.n7.game.ObjetLieu#getConditionTransmission()
   * @see #getObjetLieu()
   * @generated
   */
  EReference getObjetLieu_ConditionTransmission();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.ObjetLieu#getConditionConsommation <em>Condition Consommation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Consommation</em>'.
   * @see fr.n7.game.ObjetLieu#getConditionConsommation()
   * @see #getObjetLieu()
   * @generated
   */
  EReference getObjetLieu_ConditionConsommation();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.ObjetLieu#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.ObjetLieu#getDescription()
   * @see #getObjetLieu()
   * @generated
   */
  EAttribute getObjetLieu_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.ObjetLieu#getConditionDescription <em>Condition Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Description</em>'.
   * @see fr.n7.game.ObjetLieu#getConditionDescription()
   * @see #getObjetLieu()
   * @generated
   */
  EReference getObjetLieu_ConditionDescription();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.ObjetLieu#getTransformable <em>Transformable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transformable</em>'.
   * @see fr.n7.game.ObjetLieu#getTransformable()
   * @see #getObjetLieu()
   * @generated
   */
  EReference getObjetLieu_Transformable();

  /**
   * Returns the meta object for class '{@link fr.n7.game.ObjetsExplorateur <em>Objets Explorateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objets Explorateur</em>'.
   * @see fr.n7.game.ObjetsExplorateur
   * @generated
   */
  EClass getObjetsExplorateur();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.ObjetsExplorateur#getListeObjets <em>Liste Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Liste Objets</em>'.
   * @see fr.n7.game.ObjetsExplorateur#getListeObjets()
   * @see #getObjetsExplorateur()
   * @generated
   */
  EReference getObjetsExplorateur_ListeObjets();

  /**
   * Returns the meta object for class '{@link fr.n7.game.ObjetsLieu <em>Objets Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objets Lieu</em>'.
   * @see fr.n7.game.ObjetsLieu
   * @generated
   */
  EClass getObjetsLieu();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.ObjetsLieu#getListeObjets <em>Liste Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Liste Objets</em>'.
   * @see fr.n7.game.ObjetsLieu#getListeObjets()
   * @see #getObjetsLieu()
   * @generated
   */
  EReference getObjetsLieu_ListeObjets();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Connaissances <em>Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connaissances</em>'.
   * @see fr.n7.game.Connaissances
   * @generated
   */
  EClass getConnaissances();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Connaissances#getListeConnaissances <em>Liste Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Connaissances</em>'.
   * @see fr.n7.game.Connaissances#getListeConnaissances()
   * @see #getConnaissances()
   * @generated
   */
  EReference getConnaissances_ListeConnaissances();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Connaissance <em>Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connaissance</em>'.
   * @see fr.n7.game.Connaissance
   * @generated
   */
  EClass getConnaissance();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Connaissance#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Connaissance#getName()
   * @see #getConnaissance()
   * @generated
   */
  EAttribute getConnaissance_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Connaissance#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.Connaissance#getDescription()
   * @see #getConnaissance()
   * @generated
   */
  EAttribute getConnaissance_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Connaissance#getConditionConnaissance <em>Condition Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Connaissance</em>'.
   * @see fr.n7.game.Connaissance#getConditionConnaissance()
   * @see #getConnaissance()
   * @generated
   */
  EReference getConnaissance_ConditionConnaissance();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Conditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditions</em>'.
   * @see fr.n7.game.Conditions
   * @generated
   */
  EClass getConditions();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Conditions#getListeConditions <em>Liste Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Conditions</em>'.
   * @see fr.n7.game.Conditions#getListeConditions()
   * @see #getConditions()
   * @generated
   */
  EReference getConditions_ListeConditions();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see fr.n7.game.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Condition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Condition#getName()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Condition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see fr.n7.game.Condition#getCondition()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Condition();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Chemins <em>Chemins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chemins</em>'.
   * @see fr.n7.game.Chemins
   * @generated
   */
  EClass getChemins();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Chemins#getListeChemins <em>Liste Chemins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Liste Chemins</em>'.
   * @see fr.n7.game.Chemins#getListeChemins()
   * @see #getChemins()
   * @generated
   */
  EReference getChemins_ListeChemins();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Chemin <em>Chemin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chemin</em>'.
   * @see fr.n7.game.Chemin
   * @generated
   */
  EClass getChemin();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Chemin#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Chemin#getName()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Chemin#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.Chemin#getDescription()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Chemin#getConditionDescription <em>Condition Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Description</em>'.
   * @see fr.n7.game.Chemin#getConditionDescription()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_ConditionDescription();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Chemin#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see fr.n7.game.Chemin#getSource()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Source();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Chemin#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destination</em>'.
   * @see fr.n7.game.Chemin#getDestination()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Destination();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Chemin#getObligatoire <em>Obligatoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Obligatoire</em>'.
   * @see fr.n7.game.Chemin#getObligatoire()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Obligatoire();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Chemin#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Visible</em>'.
   * @see fr.n7.game.Chemin#getVisible()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Visible();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Chemin#getOuvert <em>Ouvert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ouvert</em>'.
   * @see fr.n7.game.Chemin#getOuvert()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Ouvert();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Chemin#getListeConnaissances <em>Liste Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Liste Connaissances</em>'.
   * @see fr.n7.game.Chemin#getListeConnaissances()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_ListeConnaissances();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Chemin#getListeObjets <em>Liste Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Liste Objets</em>'.
   * @see fr.n7.game.Chemin#getListeObjets()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_ListeObjets();

  /**
   * Returns the meta object for the reference '{@link fr.n7.game.Chemin#getListeObjetsConsommes <em>Liste Objets Consommes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Liste Objets Consommes</em>'.
   * @see fr.n7.game.Chemin#getListeObjetsConsommes()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_ListeObjetsConsommes();

  /**
   * Returns the meta object for enum '{@link fr.n7.game.TypeLieu <em>Type Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Type Lieu</em>'.
   * @see fr.n7.game.TypeLieu
   * @generated
   */
  EEnum getTypeLieu();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameFactory getGameFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.game.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.GameImpl
     * @see fr.n7.game.impl.GamePackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__NAME = eINSTANCE.getGame_Name();

    /**
     * The meta object literal for the '<em><b>Territoire Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__TERRITOIRE_ELEMENTS = eINSTANCE.getGame_TerritoireElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.territoireElementImpl <em>territoire Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.territoireElementImpl
     * @see fr.n7.game.impl.GamePackageImpl#getterritoireElement()
     * @generated
     */
    EClass TERRITOIRE_ELEMENT = eINSTANCE.getterritoireElement();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ExplorateurImpl <em>Explorateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ExplorateurImpl
     * @see fr.n7.game.impl.GamePackageImpl#getExplorateur()
     * @generated
     */
    EClass EXPLORATEUR = eINSTANCE.getExplorateur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPLORATEUR__NAME = eINSTANCE.getExplorateur_Name();

    /**
     * The meta object literal for the '<em><b>Sac</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__SAC = eINSTANCE.getExplorateur_Sac();

    /**
     * The meta object literal for the '<em><b>Connaissances</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__CONNAISSANCES = eINSTANCE.getExplorateur_Connaissances();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__POSITION = eINSTANCE.getExplorateur_Position();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.SacImpl <em>Sac</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.SacImpl
     * @see fr.n7.game.impl.GamePackageImpl#getSac()
     * @generated
     */
    EClass SAC = eINSTANCE.getSac();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SAC__TAILLE = eINSTANCE.getSac_Taille();

    /**
     * The meta object literal for the '<em><b>Sac Elements</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SAC__SAC_ELEMENTS = eINSTANCE.getSac_SacElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.LieuImpl <em>Lieu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.LieuImpl
     * @see fr.n7.game.impl.GamePackageImpl#getLieu()
     * @generated
     */
    EClass LIEU = eINSTANCE.getLieu();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__TYPE = eINSTANCE.getLieu_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__NAME = eINSTANCE.getLieu_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__DESCRIPTION = eINSTANCE.getLieu_Description();

    /**
     * The meta object literal for the '<em><b>Condition Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__CONDITION_DESCRIPTION = eINSTANCE.getLieu_ConditionDescription();

    /**
     * The meta object literal for the '<em><b>Personnes</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__PERSONNES = eINSTANCE.getLieu_Personnes();

    /**
     * The meta object literal for the '<em><b>Connaissances</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__CONNAISSANCES = eINSTANCE.getLieu_Connaissances();

    /**
     * The meta object literal for the '<em><b>Objets</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__OBJETS = eINSTANCE.getLieu_Objets();

    /**
     * The meta object literal for the '<em><b>Depot Objet</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__DEPOT_OBJET = eINSTANCE.getLieu_DepotObjet();

    /**
     * The meta object literal for the '<em><b>Liste Chemins</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__LISTE_CHEMINS = eINSTANCE.getLieu_ListeChemins();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.PersonnesImpl <em>Personnes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.PersonnesImpl
     * @see fr.n7.game.impl.GamePackageImpl#getPersonnes()
     * @generated
     */
    EClass PERSONNES = eINSTANCE.getPersonnes();

    /**
     * The meta object literal for the '<em><b>Liste Personnes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNES__LISTE_PERSONNES = eINSTANCE.getPersonnes_ListePersonnes();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.PersonneImpl <em>Personne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.PersonneImpl
     * @see fr.n7.game.impl.GamePackageImpl#getPersonne()
     * @generated
     */
    EClass PERSONNE = eINSTANCE.getPersonne();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__NAME = eINSTANCE.getPersonne_Name();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__VISIBLE = eINSTANCE.getPersonne_Visible();

    /**
     * The meta object literal for the '<em><b>Obligatoire</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__OBLIGATOIRE = eINSTANCE.getPersonne_Obligatoire();

    /**
     * The meta object literal for the '<em><b>Personne Elements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__PERSONNE_ELEMENTS = eINSTANCE.getPersonne_PersonneElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.InteractionImpl <em>Interaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.InteractionImpl
     * @see fr.n7.game.impl.GamePackageImpl#getInteraction()
     * @generated
     */
    EClass INTERACTION = eINSTANCE.getInteraction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION__NAME = eINSTANCE.getInteraction_Name();

    /**
     * The meta object literal for the '<em><b>Texte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION__TEXTE = eINSTANCE.getInteraction_Texte();

    /**
     * The meta object literal for the '<em><b>Interaction Elements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION__INTERACTION_ELEMENTS = eINSTANCE.getInteraction_InteractionElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ChoixImpl <em>Choix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ChoixImpl
     * @see fr.n7.game.impl.GamePackageImpl#getChoix()
     * @generated
     */
    EClass CHOIX = eINSTANCE.getChoix();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__NAME = eINSTANCE.getChoix_Name();

    /**
     * The meta object literal for the '<em><b>Texte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__TEXTE = eINSTANCE.getChoix_Texte();

    /**
     * The meta object literal for the '<em><b>Liste Actions</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__LISTE_ACTIONS = eINSTANCE.getChoix_ListeActions();

    /**
     * The meta object literal for the '<em><b>Choixdebut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__CHOIXDEBUT = eINSTANCE.getChoix_Choixdebut();

    /**
     * The meta object literal for the '<em><b>Conditon Choix Debut</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__CONDITON_CHOIX_DEBUT = eINSTANCE.getChoix_ConditonChoixDebut();

    /**
     * The meta object literal for the '<em><b>Choixfin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__CHOIXFIN = eINSTANCE.getChoix_Choixfin();

    /**
     * The meta object literal for the '<em><b>Condition Choix Fin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__CONDITION_CHOIX_FIN = eINSTANCE.getChoix_ConditionChoixFin();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ActionImpl
     * @see fr.n7.game.impl.GamePackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Texte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__TEXTE = eINSTANCE.getAction_Texte();

    /**
     * The meta object literal for the '<em><b>Condition Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CONDITION_ACTION = eINSTANCE.getAction_ConditionAction();

    /**
     * The meta object literal for the '<em><b>Liste Choix</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__LISTE_CHOIX = eINSTANCE.getAction_ListeChoix();

    /**
     * The meta object literal for the '<em><b>Liste Connaissances</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__LISTE_CONNAISSANCES = eINSTANCE.getAction_ListeConnaissances();

    /**
     * The meta object literal for the '<em><b>Liste Objets</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__LISTE_OBJETS = eINSTANCE.getAction_ListeObjets();

    /**
     * The meta object literal for the '<em><b>Attribution Connaissance</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ATTRIBUTION_CONNAISSANCE = eINSTANCE.getAction_AttributionConnaissance();

    /**
     * The meta object literal for the '<em><b>Attribution Objet</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ATTRIBUTION_OBJET = eINSTANCE.getAction_AttributionObjet();

    /**
     * The meta object literal for the '<em><b>Liste Objets Consommes</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__LISTE_OBJETS_CONSOMMES = eINSTANCE.getAction_ListeObjetsConsommes();

    /**
     * The meta object literal for the '<em><b>Liste Quantite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__LISTE_QUANTITE = eINSTANCE.getAction_ListeQuantite();

    /**
     * The meta object literal for the '<em><b>Consommation Objet</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CONSOMMATION_OBJET = eINSTANCE.getAction_ConsommationObjet();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ObjetExplorateurImpl <em>Objet Explorateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ObjetExplorateurImpl
     * @see fr.n7.game.impl.GamePackageImpl#getObjetExplorateur()
     * @generated
     */
    EClass OBJET_EXPLORATEUR = eINSTANCE.getObjetExplorateur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET_EXPLORATEUR__NAME = eINSTANCE.getObjetExplorateur_Name();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET_EXPLORATEUR__TAILLE = eINSTANCE.getObjetExplorateur_Taille();

    /**
     * The meta object literal for the '<em><b>Quantite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET_EXPLORATEUR__QUANTITE = eINSTANCE.getObjetExplorateur_Quantite();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET_EXPLORATEUR__DESCRIPTION = eINSTANCE.getObjetExplorateur_Description();

    /**
     * The meta object literal for the '<em><b>Condition Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET_EXPLORATEUR__CONDITION_DESCRIPTION = eINSTANCE.getObjetExplorateur_ConditionDescription();

    /**
     * The meta object literal for the '<em><b>Transformable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET_EXPLORATEUR__TRANSFORMABLE = eINSTANCE.getObjetExplorateur_Transformable();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ObjetLieuImpl <em>Objet Lieu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ObjetLieuImpl
     * @see fr.n7.game.impl.GamePackageImpl#getObjetLieu()
     * @generated
     */
    EClass OBJET_LIEU = eINSTANCE.getObjetLieu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET_LIEU__NAME = eINSTANCE.getObjetLieu_Name();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET_LIEU__TAILLE = eINSTANCE.getObjetLieu_Taille();

    /**
     * The meta object literal for the '<em><b>Quantite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET_LIEU__QUANTITE = eINSTANCE.getObjetLieu_Quantite();

    /**
     * The meta object literal for the '<em><b>Condition Transmission</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET_LIEU__CONDITION_TRANSMISSION = eINSTANCE.getObjetLieu_ConditionTransmission();

    /**
     * The meta object literal for the '<em><b>Condition Consommation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET_LIEU__CONDITION_CONSOMMATION = eINSTANCE.getObjetLieu_ConditionConsommation();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET_LIEU__DESCRIPTION = eINSTANCE.getObjetLieu_Description();

    /**
     * The meta object literal for the '<em><b>Condition Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET_LIEU__CONDITION_DESCRIPTION = eINSTANCE.getObjetLieu_ConditionDescription();

    /**
     * The meta object literal for the '<em><b>Transformable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET_LIEU__TRANSFORMABLE = eINSTANCE.getObjetLieu_Transformable();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ObjetsExplorateurImpl <em>Objets Explorateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ObjetsExplorateurImpl
     * @see fr.n7.game.impl.GamePackageImpl#getObjetsExplorateur()
     * @generated
     */
    EClass OBJETS_EXPLORATEUR = eINSTANCE.getObjetsExplorateur();

    /**
     * The meta object literal for the '<em><b>Liste Objets</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJETS_EXPLORATEUR__LISTE_OBJETS = eINSTANCE.getObjetsExplorateur_ListeObjets();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ObjetsLieuImpl <em>Objets Lieu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ObjetsLieuImpl
     * @see fr.n7.game.impl.GamePackageImpl#getObjetsLieu()
     * @generated
     */
    EClass OBJETS_LIEU = eINSTANCE.getObjetsLieu();

    /**
     * The meta object literal for the '<em><b>Liste Objets</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJETS_LIEU__LISTE_OBJETS = eINSTANCE.getObjetsLieu_ListeObjets();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ConnaissancesImpl <em>Connaissances</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ConnaissancesImpl
     * @see fr.n7.game.impl.GamePackageImpl#getConnaissances()
     * @generated
     */
    EClass CONNAISSANCES = eINSTANCE.getConnaissances();

    /**
     * The meta object literal for the '<em><b>Liste Connaissances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNAISSANCES__LISTE_CONNAISSANCES = eINSTANCE.getConnaissances_ListeConnaissances();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ConnaissanceImpl
     * @see fr.n7.game.impl.GamePackageImpl#getConnaissance()
     * @generated
     */
    EClass CONNAISSANCE = eINSTANCE.getConnaissance();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNAISSANCE__NAME = eINSTANCE.getConnaissance_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNAISSANCE__DESCRIPTION = eINSTANCE.getConnaissance_Description();

    /**
     * The meta object literal for the '<em><b>Condition Connaissance</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNAISSANCE__CONDITION_CONNAISSANCE = eINSTANCE.getConnaissance_ConditionConnaissance();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ConditionsImpl <em>Conditions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ConditionsImpl
     * @see fr.n7.game.impl.GamePackageImpl#getConditions()
     * @generated
     */
    EClass CONDITIONS = eINSTANCE.getConditions();

    /**
     * The meta object literal for the '<em><b>Liste Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONS__LISTE_CONDITIONS = eINSTANCE.getConditions_ListeConditions();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ConditionImpl
     * @see fr.n7.game.impl.GamePackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NAME = eINSTANCE.getCondition_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__CONDITION = eINSTANCE.getCondition_Condition();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.CheminsImpl <em>Chemins</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.CheminsImpl
     * @see fr.n7.game.impl.GamePackageImpl#getChemins()
     * @generated
     */
    EClass CHEMINS = eINSTANCE.getChemins();

    /**
     * The meta object literal for the '<em><b>Liste Chemins</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMINS__LISTE_CHEMINS = eINSTANCE.getChemins_ListeChemins();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.CheminImpl <em>Chemin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.CheminImpl
     * @see fr.n7.game.impl.GamePackageImpl#getChemin()
     * @generated
     */
    EClass CHEMIN = eINSTANCE.getChemin();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__NAME = eINSTANCE.getChemin_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__DESCRIPTION = eINSTANCE.getChemin_Description();

    /**
     * The meta object literal for the '<em><b>Condition Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__CONDITION_DESCRIPTION = eINSTANCE.getChemin_ConditionDescription();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__SOURCE = eINSTANCE.getChemin_Source();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__DESTINATION = eINSTANCE.getChemin_Destination();

    /**
     * The meta object literal for the '<em><b>Obligatoire</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__OBLIGATOIRE = eINSTANCE.getChemin_Obligatoire();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__VISIBLE = eINSTANCE.getChemin_Visible();

    /**
     * The meta object literal for the '<em><b>Ouvert</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__OUVERT = eINSTANCE.getChemin_Ouvert();

    /**
     * The meta object literal for the '<em><b>Liste Connaissances</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__LISTE_CONNAISSANCES = eINSTANCE.getChemin_ListeConnaissances();

    /**
     * The meta object literal for the '<em><b>Liste Objets</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__LISTE_OBJETS = eINSTANCE.getChemin_ListeObjets();

    /**
     * The meta object literal for the '<em><b>Liste Objets Consommes</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__LISTE_OBJETS_CONSOMMES = eINSTANCE.getChemin_ListeObjetsConsommes();

    /**
     * The meta object literal for the '{@link fr.n7.game.TypeLieu <em>Type Lieu</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.TypeLieu
     * @see fr.n7.game.impl.GamePackageImpl#getTypeLieu()
     * @generated
     */
    EEnum TYPE_LIEU = eINSTANCE.getTypeLieu();

  }

} //GamePackage
