/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.n7.game.GameFactory
 * @model kind="package"
 * @generated
 */
public interface GamePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "game";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.n7.fr/Game";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "game";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GamePackage eINSTANCE = fr.n7.game.impl.GamePackageImpl.init();

  /**
   * The meta object id for the '{@link fr.n7.game.impl.GameImpl <em>Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.GameImpl
   * @see fr.n7.game.impl.GamePackageImpl#getGame()
   * @generated
   */
  int GAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Game Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME__GAME_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.gameElementImpl <em>game Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.gameElementImpl
   * @see fr.n7.game.impl.GamePackageImpl#getgameElement()
   * @generated
   */
  int GAME_ELEMENT = 1;

  /**
   * The number of structural features of the '<em>game Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.TerritoireImpl <em>Territoire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.TerritoireImpl
   * @see fr.n7.game.impl.GamePackageImpl#getTerritoire()
   * @generated
   */
  int TERRITOIRE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERRITOIRE__NAME = GAME_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Territoire Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERRITOIRE__TERRITOIRE_ELEMENTS = GAME_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Territoire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TERRITOIRE_FEATURE_COUNT = GAME_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ExplorateurImpl <em>Explorateur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ExplorateurImpl
   * @see fr.n7.game.impl.GamePackageImpl#getExplorateur()
   * @generated
   */
  int EXPLORATEUR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__NAME = 0;

  /**
   * The feature id for the '<em><b>Explorateur Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR__EXPLORATEUR_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Explorateur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPLORATEUR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.SacImpl <em>Sac</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.SacImpl
   * @see fr.n7.game.impl.GamePackageImpl#getSac()
   * @generated
   */
  int SAC = 4;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAC__TAILLE = 0;

  /**
   * The feature id for the '<em><b>Sac Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAC__SAC_ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Sac</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.LieuImpl <em>Lieu</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.LieuImpl
   * @see fr.n7.game.impl.GamePackageImpl#getLieu()
   * @generated
   */
  int LIEU = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__CONDITION_DESCRIPTION = 2;

  /**
   * The feature id for the '<em><b>Lieu Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__LIEU_ELEMENTS = 3;

  /**
   * The feature id for the '<em><b>Depot Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__DEPOT_OBJET = 4;

  /**
   * The feature id for the '<em><b>Liste Chemins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU__LISTE_CHEMINS = 5;

  /**
   * The number of structural features of the '<em>Lieu</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.CheminImpl <em>Chemin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.CheminImpl
   * @see fr.n7.game.impl.GamePackageImpl#getChemin()
   * @generated
   */
  int CHEMIN = 18;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DESCRIPTION = 0;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__CONDITION_DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Destination</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DESTINATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__NAME = 3;

  /**
   * The feature id for the '<em><b>Depot Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN__DEPOT_OBJET = 4;

  /**
   * The number of structural features of the '<em>Chemin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHEMIN_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.LieuDebutImpl <em>Lieu Debut</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.LieuDebutImpl
   * @see fr.n7.game.impl.GamePackageImpl#getLieuDebut()
   * @generated
   */
  int LIEU_DEBUT = 6;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_DEBUT__DESCRIPTION = CHEMIN__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_DEBUT__CONDITION_DESCRIPTION = CHEMIN__CONDITION_DESCRIPTION;

  /**
   * The feature id for the '<em><b>Destination</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_DEBUT__DESTINATION = CHEMIN__DESTINATION;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_DEBUT__NAME = CHEMIN__NAME;

  /**
   * The feature id for the '<em><b>Depot Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_DEBUT__DEPOT_OBJET = CHEMIN__DEPOT_OBJET;

  /**
   * The feature id for the '<em><b>Lieudebut Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_DEBUT__LIEUDEBUT_ELEMENTS = CHEMIN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Liste Chemins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_DEBUT__LISTE_CHEMINS = CHEMIN_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Lieu Debut</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_DEBUT_FEATURE_COUNT = CHEMIN_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.LieuFinImpl <em>Lieu Fin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.LieuFinImpl
   * @see fr.n7.game.impl.GamePackageImpl#getLieuFin()
   * @generated
   */
  int LIEU_FIN = 7;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__DESCRIPTION = CHEMIN__DESCRIPTION;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__CONDITION_DESCRIPTION = CHEMIN__CONDITION_DESCRIPTION;

  /**
   * The feature id for the '<em><b>Destination</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__DESTINATION = CHEMIN__DESTINATION;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__NAME = CHEMIN__NAME;

  /**
   * The feature id for the '<em><b>Depot Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__DEPOT_OBJET = CHEMIN__DEPOT_OBJET;

  /**
   * The feature id for the '<em><b>Lieufin Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__LIEUFIN_ELEMENTS = CHEMIN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Obligatoire</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__OBLIGATOIRE = CHEMIN_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__VISIBLE = CHEMIN_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Ouvert</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__OUVERT = CHEMIN_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Liste Connaissances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__LISTE_CONNAISSANCES = CHEMIN_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Liste Objets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN__LISTE_OBJETS = CHEMIN_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Lieu Fin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIEU_FIN_FEATURE_COUNT = CHEMIN_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.PersonnesImpl <em>Personnes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.PersonnesImpl
   * @see fr.n7.game.impl.GamePackageImpl#getPersonnes()
   * @generated
   */
  int PERSONNES = 8;

  /**
   * The feature id for the '<em><b>Liste Personne</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNES__LISTE_PERSONNE = 0;

  /**
   * The number of structural features of the '<em>Personnes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.PersonneImpl <em>Personne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.PersonneImpl
   * @see fr.n7.game.impl.GamePackageImpl#getPersonne()
   * @generated
   */
  int PERSONNE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__NAME = 0;

  /**
   * The feature id for the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__VISIBLE = 1;

  /**
   * The feature id for the '<em><b>Obligatoire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__OBLIGATOIRE = 2;

  /**
   * The feature id for the '<em><b>Personne Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE__PERSONNE_ELEMENTS = 3;

  /**
   * The number of structural features of the '<em>Personne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERSONNE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.InteractionImpl <em>Interaction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.InteractionImpl
   * @see fr.n7.game.impl.GamePackageImpl#getInteraction()
   * @generated
   */
  int INTERACTION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__TEXTE = 1;

  /**
   * The feature id for the '<em><b>Interaction Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION__INTERACTION_ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>Interaction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERACTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ChoixImpl <em>Choix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ChoixImpl
   * @see fr.n7.game.impl.GamePackageImpl#getChoix()
   * @generated
   */
  int CHOIX = 11;

  /**
   * The feature id for the '<em><b>Texte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__TEXTE = 0;

  /**
   * The feature id for the '<em><b>Liste Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__LISTE_ACTIONS = 1;

  /**
   * The feature id for the '<em><b>Choixdebut</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CHOIXDEBUT = 2;

  /**
   * The feature id for the '<em><b>Conditon Choix Debut</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CONDITON_CHOIX_DEBUT = 3;

  /**
   * The feature id for the '<em><b>Choixfin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CHOIXFIN = 4;

  /**
   * The feature id for the '<em><b>Condition Choix Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX__CONDITION_CHOIX_FIN = 5;

  /**
   * The number of structural features of the '<em>Choix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOIX_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ActionImpl
   * @see fr.n7.game.impl.GamePackageImpl#getAction()
   * @generated
   */
  int ACTION = 12;

  /**
   * The feature id for the '<em><b>Condition Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CONDITION_ACTION = 0;

  /**
   * The feature id for the '<em><b>Liste Choix</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_CHOIX = 1;

  /**
   * The feature id for the '<em><b>Liste Connaissances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_CONNAISSANCES = 2;

  /**
   * The feature id for the '<em><b>Liste Objets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_OBJETS = 3;

  /**
   * The feature id for the '<em><b>Attribution Connaissance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ATTRIBUTION_CONNAISSANCE = 4;

  /**
   * The feature id for the '<em><b>Attribution Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ATTRIBUTION_OBJET = 5;

  /**
   * The feature id for the '<em><b>Liste Objets Consommes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__LISTE_OBJETS_CONSOMMES = 6;

  /**
   * The feature id for the '<em><b>Consommation Objet</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CONSOMMATION_OBJET = 7;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ObjetImpl <em>Objet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ObjetImpl
   * @see fr.n7.game.impl.GamePackageImpl#getObjet()
   * @generated
   */
  int OBJET = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__NAME = 0;

  /**
   * The feature id for the '<em><b>Taille</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__TAILLE = 1;

  /**
   * The feature id for the '<em><b>Quantite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__QUANTITE = 2;

  /**
   * The feature id for the '<em><b>Condition Transmission</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__CONDITION_TRANSMISSION = 3;

  /**
   * The feature id for the '<em><b>Condition Consommation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__CONDITION_CONSOMMATION = 4;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__DESCRIPTION = 5;

  /**
   * The feature id for the '<em><b>Condition Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__CONDITION_DESCRIPTION = 6;

  /**
   * The feature id for the '<em><b>Transformable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET__TRANSFORMABLE = 7;

  /**
   * The number of structural features of the '<em>Objet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJET_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ObjetsImpl <em>Objets</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ObjetsImpl
   * @see fr.n7.game.impl.GamePackageImpl#getObjets()
   * @generated
   */
  int OBJETS = 14;

  /**
   * The feature id for the '<em><b>Liste Objets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJETS__LISTE_OBJETS = 0;

  /**
   * The number of structural features of the '<em>Objets</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJETS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ConnaissancesImpl <em>Connaissances</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ConnaissancesImpl
   * @see fr.n7.game.impl.GamePackageImpl#getConnaissances()
   * @generated
   */
  int CONNAISSANCES = 15;

  /**
   * The feature id for the '<em><b>Liste Connaissances</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCES__LISTE_CONNAISSANCES = 0;

  /**
   * The number of structural features of the '<em>Connaissances</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ConnaissanceImpl
   * @see fr.n7.game.impl.GamePackageImpl#getConnaissance()
   * @generated
   */
  int CONNAISSANCE = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Condition Connaissance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE__CONDITION_CONNAISSANCE = 2;

  /**
   * The number of structural features of the '<em>Connaissance</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNAISSANCE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.n7.game.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.n7.game.impl.ConditionImpl
   * @see fr.n7.game.impl.GamePackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CONDITION = 1;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link fr.n7.game.Game <em>Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game</em>'.
   * @see fr.n7.game.Game
   * @generated
   */
  EClass getGame();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Game#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Game#getName()
   * @see #getGame()
   * @generated
   */
  EAttribute getGame_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Game#getGameElements <em>Game Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Game Elements</em>'.
   * @see fr.n7.game.Game#getGameElements()
   * @see #getGame()
   * @generated
   */
  EReference getGame_GameElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.gameElement <em>game Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>game Element</em>'.
   * @see fr.n7.game.gameElement
   * @generated
   */
  EClass getgameElement();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Territoire <em>Territoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Territoire</em>'.
   * @see fr.n7.game.Territoire
   * @generated
   */
  EClass getTerritoire();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Territoire#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Territoire#getName()
   * @see #getTerritoire()
   * @generated
   */
  EAttribute getTerritoire_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Territoire#getTerritoireElements <em>Territoire Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Territoire Elements</em>'.
   * @see fr.n7.game.Territoire#getTerritoireElements()
   * @see #getTerritoire()
   * @generated
   */
  EReference getTerritoire_TerritoireElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Explorateur <em>Explorateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Explorateur</em>'.
   * @see fr.n7.game.Explorateur
   * @generated
   */
  EClass getExplorateur();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Explorateur#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Explorateur#getName()
   * @see #getExplorateur()
   * @generated
   */
  EAttribute getExplorateur_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Explorateur#getExplorateurElements <em>Explorateur Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Explorateur Elements</em>'.
   * @see fr.n7.game.Explorateur#getExplorateurElements()
   * @see #getExplorateur()
   * @generated
   */
  EReference getExplorateur_ExplorateurElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Sac <em>Sac</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sac</em>'.
   * @see fr.n7.game.Sac
   * @generated
   */
  EClass getSac();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Sac#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see fr.n7.game.Sac#getTaille()
   * @see #getSac()
   * @generated
   */
  EAttribute getSac_Taille();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Sac#getSacElements <em>Sac Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sac Elements</em>'.
   * @see fr.n7.game.Sac#getSacElements()
   * @see #getSac()
   * @generated
   */
  EReference getSac_SacElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Lieu <em>Lieu</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lieu</em>'.
   * @see fr.n7.game.Lieu
   * @generated
   */
  EClass getLieu();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Lieu#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Lieu#getName()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Lieu#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.Lieu#getDescription()
   * @see #getLieu()
   * @generated
   */
  EAttribute getLieu_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Lieu#getConditionDescription <em>Condition Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Description</em>'.
   * @see fr.n7.game.Lieu#getConditionDescription()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_ConditionDescription();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Lieu#getLieuElements <em>Lieu Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lieu Elements</em>'.
   * @see fr.n7.game.Lieu#getLieuElements()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_LieuElements();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Lieu#getDepotObjet <em>Depot Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Depot Objet</em>'.
   * @see fr.n7.game.Lieu#getDepotObjet()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_DepotObjet();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Lieu#getListeChemins <em>Liste Chemins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Chemins</em>'.
   * @see fr.n7.game.Lieu#getListeChemins()
   * @see #getLieu()
   * @generated
   */
  EReference getLieu_ListeChemins();

  /**
   * Returns the meta object for class '{@link fr.n7.game.LieuDebut <em>Lieu Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lieu Debut</em>'.
   * @see fr.n7.game.LieuDebut
   * @generated
   */
  EClass getLieuDebut();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.LieuDebut#getLieudebutElements <em>Lieudebut Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lieudebut Elements</em>'.
   * @see fr.n7.game.LieuDebut#getLieudebutElements()
   * @see #getLieuDebut()
   * @generated
   */
  EReference getLieuDebut_LieudebutElements();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.LieuDebut#getListeChemins <em>Liste Chemins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Chemins</em>'.
   * @see fr.n7.game.LieuDebut#getListeChemins()
   * @see #getLieuDebut()
   * @generated
   */
  EReference getLieuDebut_ListeChemins();

  /**
   * Returns the meta object for class '{@link fr.n7.game.LieuFin <em>Lieu Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lieu Fin</em>'.
   * @see fr.n7.game.LieuFin
   * @generated
   */
  EClass getLieuFin();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.LieuFin#getLieufinElements <em>Lieufin Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lieufin Elements</em>'.
   * @see fr.n7.game.LieuFin#getLieufinElements()
   * @see #getLieuFin()
   * @generated
   */
  EReference getLieuFin_LieufinElements();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.LieuFin#getObligatoire <em>Obligatoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Obligatoire</em>'.
   * @see fr.n7.game.LieuFin#getObligatoire()
   * @see #getLieuFin()
   * @generated
   */
  EReference getLieuFin_Obligatoire();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.LieuFin#getVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Visible</em>'.
   * @see fr.n7.game.LieuFin#getVisible()
   * @see #getLieuFin()
   * @generated
   */
  EReference getLieuFin_Visible();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.LieuFin#getOuvert <em>Ouvert</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ouvert</em>'.
   * @see fr.n7.game.LieuFin#getOuvert()
   * @see #getLieuFin()
   * @generated
   */
  EReference getLieuFin_Ouvert();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.LieuFin#getListeConnaissances <em>Liste Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Connaissances</em>'.
   * @see fr.n7.game.LieuFin#getListeConnaissances()
   * @see #getLieuFin()
   * @generated
   */
  EReference getLieuFin_ListeConnaissances();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.LieuFin#getListeObjets <em>Liste Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Objets</em>'.
   * @see fr.n7.game.LieuFin#getListeObjets()
   * @see #getLieuFin()
   * @generated
   */
  EReference getLieuFin_ListeObjets();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Personnes <em>Personnes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Personnes</em>'.
   * @see fr.n7.game.Personnes
   * @generated
   */
  EClass getPersonnes();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Personnes#getListePersonne <em>Liste Personne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Personne</em>'.
   * @see fr.n7.game.Personnes#getListePersonne()
   * @see #getPersonnes()
   * @generated
   */
  EReference getPersonnes_ListePersonne();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Personne <em>Personne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Personne</em>'.
   * @see fr.n7.game.Personne
   * @generated
   */
  EClass getPersonne();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Personne#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Personne#getName()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Personne#isVisible <em>Visible</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visible</em>'.
   * @see fr.n7.game.Personne#isVisible()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Visible();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Personne#isObligatoire <em>Obligatoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Obligatoire</em>'.
   * @see fr.n7.game.Personne#isObligatoire()
   * @see #getPersonne()
   * @generated
   */
  EAttribute getPersonne_Obligatoire();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Personne#getPersonneElements <em>Personne Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Personne Elements</em>'.
   * @see fr.n7.game.Personne#getPersonneElements()
   * @see #getPersonne()
   * @generated
   */
  EReference getPersonne_PersonneElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Interaction <em>Interaction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interaction</em>'.
   * @see fr.n7.game.Interaction
   * @generated
   */
  EClass getInteraction();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Interaction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Interaction#getName()
   * @see #getInteraction()
   * @generated
   */
  EAttribute getInteraction_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Interaction#getTexte <em>Texte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texte</em>'.
   * @see fr.n7.game.Interaction#getTexte()
   * @see #getInteraction()
   * @generated
   */
  EAttribute getInteraction_Texte();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Interaction#getInteractionElements <em>Interaction Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Interaction Elements</em>'.
   * @see fr.n7.game.Interaction#getInteractionElements()
   * @see #getInteraction()
   * @generated
   */
  EReference getInteraction_InteractionElements();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Choix <em>Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choix</em>'.
   * @see fr.n7.game.Choix
   * @generated
   */
  EClass getChoix();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Choix#getTexte <em>Texte</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Texte</em>'.
   * @see fr.n7.game.Choix#getTexte()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Texte();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Choix#getListeActions <em>Liste Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Actions</em>'.
   * @see fr.n7.game.Choix#getListeActions()
   * @see #getChoix()
   * @generated
   */
  EReference getChoix_ListeActions();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Choix#getChoixdebut <em>Choixdebut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Choixdebut</em>'.
   * @see fr.n7.game.Choix#getChoixdebut()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Choixdebut();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Choix#getConditonChoixDebut <em>Conditon Choix Debut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conditon Choix Debut</em>'.
   * @see fr.n7.game.Choix#getConditonChoixDebut()
   * @see #getChoix()
   * @generated
   */
  EReference getChoix_ConditonChoixDebut();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Choix#getChoixfin <em>Choixfin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Choixfin</em>'.
   * @see fr.n7.game.Choix#getChoixfin()
   * @see #getChoix()
   * @generated
   */
  EAttribute getChoix_Choixfin();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Choix#getConditionChoixFin <em>Condition Choix Fin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Choix Fin</em>'.
   * @see fr.n7.game.Choix#getConditionChoixFin()
   * @see #getChoix()
   * @generated
   */
  EReference getChoix_ConditionChoixFin();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see fr.n7.game.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Action#getConditionAction <em>Condition Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Action</em>'.
   * @see fr.n7.game.Action#getConditionAction()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ConditionAction();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Action#getListeChoix <em>Liste Choix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Choix</em>'.
   * @see fr.n7.game.Action#getListeChoix()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ListeChoix();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Action#getListeConnaissances <em>Liste Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Connaissances</em>'.
   * @see fr.n7.game.Action#getListeConnaissances()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ListeConnaissances();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Action#getListeObjets <em>Liste Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Objets</em>'.
   * @see fr.n7.game.Action#getListeObjets()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ListeObjets();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Action#getAttributionConnaissance <em>Attribution Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribution Connaissance</em>'.
   * @see fr.n7.game.Action#getAttributionConnaissance()
   * @see #getAction()
   * @generated
   */
  EReference getAction_AttributionConnaissance();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Action#getAttributionObjet <em>Attribution Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attribution Objet</em>'.
   * @see fr.n7.game.Action#getAttributionObjet()
   * @see #getAction()
   * @generated
   */
  EReference getAction_AttributionObjet();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Action#getListeObjetsConsommes <em>Liste Objets Consommes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Objets Consommes</em>'.
   * @see fr.n7.game.Action#getListeObjetsConsommes()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ListeObjetsConsommes();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Action#getConsommationObjet <em>Consommation Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Consommation Objet</em>'.
   * @see fr.n7.game.Action#getConsommationObjet()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ConsommationObjet();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Objet <em>Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objet</em>'.
   * @see fr.n7.game.Objet
   * @generated
   */
  EClass getObjet();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Objet#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Objet#getName()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Objet#getTaille <em>Taille</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Taille</em>'.
   * @see fr.n7.game.Objet#getTaille()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Taille();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Objet#getQuantite <em>Quantite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantite</em>'.
   * @see fr.n7.game.Objet#getQuantite()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Quantite();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Objet#getConditionTransmission <em>Condition Transmission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Transmission</em>'.
   * @see fr.n7.game.Objet#getConditionTransmission()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_ConditionTransmission();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Objet#getConditionConsommation <em>Condition Consommation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Consommation</em>'.
   * @see fr.n7.game.Objet#getConditionConsommation()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_ConditionConsommation();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Objet#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.Objet#getDescription()
   * @see #getObjet()
   * @generated
   */
  EAttribute getObjet_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Objet#getConditionDescription <em>Condition Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Description</em>'.
   * @see fr.n7.game.Objet#getConditionDescription()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_ConditionDescription();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Objet#getTransformable <em>Transformable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Transformable</em>'.
   * @see fr.n7.game.Objet#getTransformable()
   * @see #getObjet()
   * @generated
   */
  EReference getObjet_Transformable();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Objets <em>Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Objets</em>'.
   * @see fr.n7.game.Objets
   * @generated
   */
  EClass getObjets();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Objets#getListeObjets <em>Liste Objets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Objets</em>'.
   * @see fr.n7.game.Objets#getListeObjets()
   * @see #getObjets()
   * @generated
   */
  EReference getObjets_ListeObjets();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Connaissances <em>Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connaissances</em>'.
   * @see fr.n7.game.Connaissances
   * @generated
   */
  EClass getConnaissances();

  /**
   * Returns the meta object for the containment reference list '{@link fr.n7.game.Connaissances#getListeConnaissances <em>Liste Connaissances</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Liste Connaissances</em>'.
   * @see fr.n7.game.Connaissances#getListeConnaissances()
   * @see #getConnaissances()
   * @generated
   */
  EReference getConnaissances_ListeConnaissances();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Connaissance <em>Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connaissance</em>'.
   * @see fr.n7.game.Connaissance
   * @generated
   */
  EClass getConnaissance();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Connaissance#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Connaissance#getName()
   * @see #getConnaissance()
   * @generated
   */
  EAttribute getConnaissance_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Connaissance#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.Connaissance#getDescription()
   * @see #getConnaissance()
   * @generated
   */
  EAttribute getConnaissance_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Connaissance#getConditionConnaissance <em>Condition Connaissance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Connaissance</em>'.
   * @see fr.n7.game.Connaissance#getConditionConnaissance()
   * @see #getConnaissance()
   * @generated
   */
  EReference getConnaissance_ConditionConnaissance();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see fr.n7.game.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Condition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Condition#getName()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Condition#isCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see fr.n7.game.Condition#isCondition()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Condition();

  /**
   * Returns the meta object for class '{@link fr.n7.game.Chemin <em>Chemin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chemin</em>'.
   * @see fr.n7.game.Chemin
   * @generated
   */
  EClass getChemin();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Chemin#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.n7.game.Chemin#getDescription()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Chemin#getConditionDescription <em>Condition Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition Description</em>'.
   * @see fr.n7.game.Chemin#getConditionDescription()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_ConditionDescription();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Chemin#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Destination</em>'.
   * @see fr.n7.game.Chemin#getDestination()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_Destination();

  /**
   * Returns the meta object for the attribute '{@link fr.n7.game.Chemin#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.n7.game.Chemin#getName()
   * @see #getChemin()
   * @generated
   */
  EAttribute getChemin_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.n7.game.Chemin#getDepotObjet <em>Depot Objet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Depot Objet</em>'.
   * @see fr.n7.game.Chemin#getDepotObjet()
   * @see #getChemin()
   * @generated
   */
  EReference getChemin_DepotObjet();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameFactory getGameFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.n7.game.impl.GameImpl <em>Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.GameImpl
     * @see fr.n7.game.impl.GamePackageImpl#getGame()
     * @generated
     */
    EClass GAME = eINSTANCE.getGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME__NAME = eINSTANCE.getGame_Name();

    /**
     * The meta object literal for the '<em><b>Game Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME__GAME_ELEMENTS = eINSTANCE.getGame_GameElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.gameElementImpl <em>game Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.gameElementImpl
     * @see fr.n7.game.impl.GamePackageImpl#getgameElement()
     * @generated
     */
    EClass GAME_ELEMENT = eINSTANCE.getgameElement();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.TerritoireImpl <em>Territoire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.TerritoireImpl
     * @see fr.n7.game.impl.GamePackageImpl#getTerritoire()
     * @generated
     */
    EClass TERRITOIRE = eINSTANCE.getTerritoire();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TERRITOIRE__NAME = eINSTANCE.getTerritoire_Name();

    /**
     * The meta object literal for the '<em><b>Territoire Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TERRITOIRE__TERRITOIRE_ELEMENTS = eINSTANCE.getTerritoire_TerritoireElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ExplorateurImpl <em>Explorateur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ExplorateurImpl
     * @see fr.n7.game.impl.GamePackageImpl#getExplorateur()
     * @generated
     */
    EClass EXPLORATEUR = eINSTANCE.getExplorateur();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPLORATEUR__NAME = eINSTANCE.getExplorateur_Name();

    /**
     * The meta object literal for the '<em><b>Explorateur Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPLORATEUR__EXPLORATEUR_ELEMENTS = eINSTANCE.getExplorateur_ExplorateurElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.SacImpl <em>Sac</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.SacImpl
     * @see fr.n7.game.impl.GamePackageImpl#getSac()
     * @generated
     */
    EClass SAC = eINSTANCE.getSac();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SAC__TAILLE = eINSTANCE.getSac_Taille();

    /**
     * The meta object literal for the '<em><b>Sac Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SAC__SAC_ELEMENTS = eINSTANCE.getSac_SacElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.LieuImpl <em>Lieu</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.LieuImpl
     * @see fr.n7.game.impl.GamePackageImpl#getLieu()
     * @generated
     */
    EClass LIEU = eINSTANCE.getLieu();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__NAME = eINSTANCE.getLieu_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIEU__DESCRIPTION = eINSTANCE.getLieu_Description();

    /**
     * The meta object literal for the '<em><b>Condition Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__CONDITION_DESCRIPTION = eINSTANCE.getLieu_ConditionDescription();

    /**
     * The meta object literal for the '<em><b>Lieu Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__LIEU_ELEMENTS = eINSTANCE.getLieu_LieuElements();

    /**
     * The meta object literal for the '<em><b>Depot Objet</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__DEPOT_OBJET = eINSTANCE.getLieu_DepotObjet();

    /**
     * The meta object literal for the '<em><b>Liste Chemins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU__LISTE_CHEMINS = eINSTANCE.getLieu_ListeChemins();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.LieuDebutImpl <em>Lieu Debut</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.LieuDebutImpl
     * @see fr.n7.game.impl.GamePackageImpl#getLieuDebut()
     * @generated
     */
    EClass LIEU_DEBUT = eINSTANCE.getLieuDebut();

    /**
     * The meta object literal for the '<em><b>Lieudebut Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU_DEBUT__LIEUDEBUT_ELEMENTS = eINSTANCE.getLieuDebut_LieudebutElements();

    /**
     * The meta object literal for the '<em><b>Liste Chemins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU_DEBUT__LISTE_CHEMINS = eINSTANCE.getLieuDebut_ListeChemins();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.LieuFinImpl <em>Lieu Fin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.LieuFinImpl
     * @see fr.n7.game.impl.GamePackageImpl#getLieuFin()
     * @generated
     */
    EClass LIEU_FIN = eINSTANCE.getLieuFin();

    /**
     * The meta object literal for the '<em><b>Lieufin Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU_FIN__LIEUFIN_ELEMENTS = eINSTANCE.getLieuFin_LieufinElements();

    /**
     * The meta object literal for the '<em><b>Obligatoire</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU_FIN__OBLIGATOIRE = eINSTANCE.getLieuFin_Obligatoire();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU_FIN__VISIBLE = eINSTANCE.getLieuFin_Visible();

    /**
     * The meta object literal for the '<em><b>Ouvert</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU_FIN__OUVERT = eINSTANCE.getLieuFin_Ouvert();

    /**
     * The meta object literal for the '<em><b>Liste Connaissances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU_FIN__LISTE_CONNAISSANCES = eINSTANCE.getLieuFin_ListeConnaissances();

    /**
     * The meta object literal for the '<em><b>Liste Objets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIEU_FIN__LISTE_OBJETS = eINSTANCE.getLieuFin_ListeObjets();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.PersonnesImpl <em>Personnes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.PersonnesImpl
     * @see fr.n7.game.impl.GamePackageImpl#getPersonnes()
     * @generated
     */
    EClass PERSONNES = eINSTANCE.getPersonnes();

    /**
     * The meta object literal for the '<em><b>Liste Personne</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNES__LISTE_PERSONNE = eINSTANCE.getPersonnes_ListePersonne();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.PersonneImpl <em>Personne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.PersonneImpl
     * @see fr.n7.game.impl.GamePackageImpl#getPersonne()
     * @generated
     */
    EClass PERSONNE = eINSTANCE.getPersonne();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__NAME = eINSTANCE.getPersonne_Name();

    /**
     * The meta object literal for the '<em><b>Visible</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__VISIBLE = eINSTANCE.getPersonne_Visible();

    /**
     * The meta object literal for the '<em><b>Obligatoire</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERSONNE__OBLIGATOIRE = eINSTANCE.getPersonne_Obligatoire();

    /**
     * The meta object literal for the '<em><b>Personne Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERSONNE__PERSONNE_ELEMENTS = eINSTANCE.getPersonne_PersonneElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.InteractionImpl <em>Interaction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.InteractionImpl
     * @see fr.n7.game.impl.GamePackageImpl#getInteraction()
     * @generated
     */
    EClass INTERACTION = eINSTANCE.getInteraction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION__NAME = eINSTANCE.getInteraction_Name();

    /**
     * The meta object literal for the '<em><b>Texte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERACTION__TEXTE = eINSTANCE.getInteraction_Texte();

    /**
     * The meta object literal for the '<em><b>Interaction Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTERACTION__INTERACTION_ELEMENTS = eINSTANCE.getInteraction_InteractionElements();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ChoixImpl <em>Choix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ChoixImpl
     * @see fr.n7.game.impl.GamePackageImpl#getChoix()
     * @generated
     */
    EClass CHOIX = eINSTANCE.getChoix();

    /**
     * The meta object literal for the '<em><b>Texte</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__TEXTE = eINSTANCE.getChoix_Texte();

    /**
     * The meta object literal for the '<em><b>Liste Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__LISTE_ACTIONS = eINSTANCE.getChoix_ListeActions();

    /**
     * The meta object literal for the '<em><b>Choixdebut</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__CHOIXDEBUT = eINSTANCE.getChoix_Choixdebut();

    /**
     * The meta object literal for the '<em><b>Conditon Choix Debut</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__CONDITON_CHOIX_DEBUT = eINSTANCE.getChoix_ConditonChoixDebut();

    /**
     * The meta object literal for the '<em><b>Choixfin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOIX__CHOIXFIN = eINSTANCE.getChoix_Choixfin();

    /**
     * The meta object literal for the '<em><b>Condition Choix Fin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOIX__CONDITION_CHOIX_FIN = eINSTANCE.getChoix_ConditionChoixFin();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ActionImpl
     * @see fr.n7.game.impl.GamePackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Condition Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CONDITION_ACTION = eINSTANCE.getAction_ConditionAction();

    /**
     * The meta object literal for the '<em><b>Liste Choix</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__LISTE_CHOIX = eINSTANCE.getAction_ListeChoix();

    /**
     * The meta object literal for the '<em><b>Liste Connaissances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__LISTE_CONNAISSANCES = eINSTANCE.getAction_ListeConnaissances();

    /**
     * The meta object literal for the '<em><b>Liste Objets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__LISTE_OBJETS = eINSTANCE.getAction_ListeObjets();

    /**
     * The meta object literal for the '<em><b>Attribution Connaissance</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ATTRIBUTION_CONNAISSANCE = eINSTANCE.getAction_AttributionConnaissance();

    /**
     * The meta object literal for the '<em><b>Attribution Objet</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ATTRIBUTION_OBJET = eINSTANCE.getAction_AttributionObjet();

    /**
     * The meta object literal for the '<em><b>Liste Objets Consommes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__LISTE_OBJETS_CONSOMMES = eINSTANCE.getAction_ListeObjetsConsommes();

    /**
     * The meta object literal for the '<em><b>Consommation Objet</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CONSOMMATION_OBJET = eINSTANCE.getAction_ConsommationObjet();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ObjetImpl <em>Objet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ObjetImpl
     * @see fr.n7.game.impl.GamePackageImpl#getObjet()
     * @generated
     */
    EClass OBJET = eINSTANCE.getObjet();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__NAME = eINSTANCE.getObjet_Name();

    /**
     * The meta object literal for the '<em><b>Taille</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__TAILLE = eINSTANCE.getObjet_Taille();

    /**
     * The meta object literal for the '<em><b>Quantite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__QUANTITE = eINSTANCE.getObjet_Quantite();

    /**
     * The meta object literal for the '<em><b>Condition Transmission</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__CONDITION_TRANSMISSION = eINSTANCE.getObjet_ConditionTransmission();

    /**
     * The meta object literal for the '<em><b>Condition Consommation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__CONDITION_CONSOMMATION = eINSTANCE.getObjet_ConditionConsommation();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJET__DESCRIPTION = eINSTANCE.getObjet_Description();

    /**
     * The meta object literal for the '<em><b>Condition Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__CONDITION_DESCRIPTION = eINSTANCE.getObjet_ConditionDescription();

    /**
     * The meta object literal for the '<em><b>Transformable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJET__TRANSFORMABLE = eINSTANCE.getObjet_Transformable();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ObjetsImpl <em>Objets</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ObjetsImpl
     * @see fr.n7.game.impl.GamePackageImpl#getObjets()
     * @generated
     */
    EClass OBJETS = eINSTANCE.getObjets();

    /**
     * The meta object literal for the '<em><b>Liste Objets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJETS__LISTE_OBJETS = eINSTANCE.getObjets_ListeObjets();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ConnaissancesImpl <em>Connaissances</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ConnaissancesImpl
     * @see fr.n7.game.impl.GamePackageImpl#getConnaissances()
     * @generated
     */
    EClass CONNAISSANCES = eINSTANCE.getConnaissances();

    /**
     * The meta object literal for the '<em><b>Liste Connaissances</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNAISSANCES__LISTE_CONNAISSANCES = eINSTANCE.getConnaissances_ListeConnaissances();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ConnaissanceImpl <em>Connaissance</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ConnaissanceImpl
     * @see fr.n7.game.impl.GamePackageImpl#getConnaissance()
     * @generated
     */
    EClass CONNAISSANCE = eINSTANCE.getConnaissance();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNAISSANCE__NAME = eINSTANCE.getConnaissance_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNAISSANCE__DESCRIPTION = eINSTANCE.getConnaissance_Description();

    /**
     * The meta object literal for the '<em><b>Condition Connaissance</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNAISSANCE__CONDITION_CONNAISSANCE = eINSTANCE.getConnaissance_ConditionConnaissance();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.ConditionImpl
     * @see fr.n7.game.impl.GamePackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NAME = eINSTANCE.getCondition_Name();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__CONDITION = eINSTANCE.getCondition_Condition();

    /**
     * The meta object literal for the '{@link fr.n7.game.impl.CheminImpl <em>Chemin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.n7.game.impl.CheminImpl
     * @see fr.n7.game.impl.GamePackageImpl#getChemin()
     * @generated
     */
    EClass CHEMIN = eINSTANCE.getChemin();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__DESCRIPTION = eINSTANCE.getChemin_Description();

    /**
     * The meta object literal for the '<em><b>Condition Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__CONDITION_DESCRIPTION = eINSTANCE.getChemin_ConditionDescription();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__DESTINATION = eINSTANCE.getChemin_Destination();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHEMIN__NAME = eINSTANCE.getChemin_Name();

    /**
     * The meta object literal for the '<em><b>Depot Objet</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHEMIN__DEPOT_OBJET = eINSTANCE.getChemin_DepotObjet();

  }

} //GamePackage
