/**
 * generated by Xtext 2.23.0
 */
package fr.n7.game;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lieu Fin</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.game.LieuFin#getLieufinElements <em>Lieufin Elements</em>}</li>
 *   <li>{@link fr.n7.game.LieuFin#getObligatoire <em>Obligatoire</em>}</li>
 *   <li>{@link fr.n7.game.LieuFin#getVisible <em>Visible</em>}</li>
 *   <li>{@link fr.n7.game.LieuFin#getOuvert <em>Ouvert</em>}</li>
 *   <li>{@link fr.n7.game.LieuFin#getListeConnaissances <em>Liste Connaissances</em>}</li>
 *   <li>{@link fr.n7.game.LieuFin#getListeObjets <em>Liste Objets</em>}</li>
 * </ul>
 *
 * @see fr.n7.game.GamePackage#getLieuFin()
 * @model
 * @generated
 */
public interface LieuFin extends Chemin
{
  /**
   * Returns the value of the '<em><b>Lieufin Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lieufin Elements</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getLieuFin_LieufinElements()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getLieufinElements();

  /**
   * Returns the value of the '<em><b>Obligatoire</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligatoire</em>' containment reference.
   * @see #setObligatoire(Condition)
   * @see fr.n7.game.GamePackage#getLieuFin_Obligatoire()
   * @model containment="true"
   * @generated
   */
  Condition getObligatoire();

  /**
   * Sets the value of the '{@link fr.n7.game.LieuFin#getObligatoire <em>Obligatoire</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obligatoire</em>' containment reference.
   * @see #getObligatoire()
   * @generated
   */
  void setObligatoire(Condition value);

  /**
   * Returns the value of the '<em><b>Visible</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible</em>' containment reference.
   * @see #setVisible(Condition)
   * @see fr.n7.game.GamePackage#getLieuFin_Visible()
   * @model containment="true"
   * @generated
   */
  Condition getVisible();

  /**
   * Sets the value of the '{@link fr.n7.game.LieuFin#getVisible <em>Visible</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible</em>' containment reference.
   * @see #getVisible()
   * @generated
   */
  void setVisible(Condition value);

  /**
   * Returns the value of the '<em><b>Ouvert</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ouvert</em>' containment reference.
   * @see #setOuvert(Condition)
   * @see fr.n7.game.GamePackage#getLieuFin_Ouvert()
   * @model containment="true"
   * @generated
   */
  Condition getOuvert();

  /**
   * Sets the value of the '{@link fr.n7.game.LieuFin#getOuvert <em>Ouvert</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ouvert</em>' containment reference.
   * @see #getOuvert()
   * @generated
   */
  void setOuvert(Condition value);

  /**
   * Returns the value of the '<em><b>Liste Connaissances</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.game.Connaissance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Liste Connaissances</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getLieuFin_ListeConnaissances()
   * @model containment="true"
   * @generated
   */
  EList<Connaissance> getListeConnaissances();

  /**
   * Returns the value of the '<em><b>Liste Objets</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.game.Objet}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Liste Objets</em>' containment reference list.
   * @see fr.n7.game.GamePackage#getLieuFin_ListeObjets()
   * @model containment="true"
   * @generated
   */
  EList<Objet> getListeObjets();

} // LieuFin
