/*
 * generated by Xtext 2.23.0
 */
package fr.n7.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GameGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class GameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Game");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTerritoireKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTerritoireElementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTerritoireElementsTerritoireElementParserRuleCall_3_0 = (RuleCall)cTerritoireElementsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Game:
		//	'territoire'
		//	name=ID
		//	'{'
		//	territoireElements+=territoireElement+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'territoire' name=ID '{' territoireElements+=territoireElement+ '}'
		public Group getGroup() { return cGroup; }
		
		//'territoire'
		public Keyword getTerritoireKeyword_0() { return cTerritoireKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//territoireElements+=territoireElement+
		public Assignment getTerritoireElementsAssignment_3() { return cTerritoireElementsAssignment_3; }
		
		//territoireElement
		public RuleCall getTerritoireElementsTerritoireElementParserRuleCall_3_0() { return cTerritoireElementsTerritoireElementParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class TerritoireElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.territoireElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExplorateurParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLieuParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cObjetsExplorateurParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cObjetsLieuParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cConnaissancesParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cPersonnesParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cCheminsParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cConditionsParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//territoireElement:
		//	Explorateur | Lieu | ObjetsExplorateur | ObjetsLieu | Connaissances | Personnes | Chemins | Conditions;
		@Override public ParserRule getRule() { return rule; }
		
		//Explorateur | Lieu | ObjetsExplorateur | ObjetsLieu | Connaissances | Personnes | Chemins | Conditions
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Explorateur
		public RuleCall getExplorateurParserRuleCall_0() { return cExplorateurParserRuleCall_0; }
		
		//Lieu
		public RuleCall getLieuParserRuleCall_1() { return cLieuParserRuleCall_1; }
		
		//ObjetsExplorateur
		public RuleCall getObjetsExplorateurParserRuleCall_2() { return cObjetsExplorateurParserRuleCall_2; }
		
		//ObjetsLieu
		public RuleCall getObjetsLieuParserRuleCall_3() { return cObjetsLieuParserRuleCall_3; }
		
		//Connaissances
		public RuleCall getConnaissancesParserRuleCall_4() { return cConnaissancesParserRuleCall_4; }
		
		//Personnes
		public RuleCall getPersonnesParserRuleCall_5() { return cPersonnesParserRuleCall_5; }
		
		//Chemins
		public RuleCall getCheminsParserRuleCall_6() { return cCheminsParserRuleCall_6; }
		
		//Conditions
		public RuleCall getConditionsParserRuleCall_7() { return cConditionsParserRuleCall_7; }
	}
	public class ExplorateurElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Explorateur");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExplorateurKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSacAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSacSacParserRuleCall_3_0 = (RuleCall)cSacAssignment_3.eContents().get(0);
		private final Keyword cConnaissancesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cConnaissancesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cConnaissancesConnaissanceCrossReference_5_0 = (CrossReference)cConnaissancesAssignment_5.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_5_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_5_0.eContents().get(1);
		private final Keyword cPositionKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPositionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cPositionLieuCrossReference_7_0 = (CrossReference)cPositionAssignment_7.eContents().get(0);
		private final RuleCall cPositionLieuIDTerminalRuleCall_7_0_1 = (RuleCall)cPositionLieuCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Explorateur:
		//	'explorateur'
		//	name=ID
		//	'{'
		//	sac=Sac
		//	'connaissances' connaissances=[Connaissance]*
		//	'position' position=[Lieu]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'explorateur' name=ID '{' sac=Sac 'connaissances' connaissances=[Connaissance]* 'position' position=[Lieu] '}'
		public Group getGroup() { return cGroup; }
		
		//'explorateur'
		public Keyword getExplorateurKeyword_0() { return cExplorateurKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//sac=Sac
		public Assignment getSacAssignment_3() { return cSacAssignment_3; }
		
		//Sac
		public RuleCall getSacSacParserRuleCall_3_0() { return cSacSacParserRuleCall_3_0; }
		
		//'connaissances'
		public Keyword getConnaissancesKeyword_4() { return cConnaissancesKeyword_4; }
		
		//connaissances=[Connaissance]*
		public Assignment getConnaissancesAssignment_5() { return cConnaissancesAssignment_5; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_5_0() { return cConnaissancesConnaissanceCrossReference_5_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_5_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_5_0_1; }
		
		//'position'
		public Keyword getPositionKeyword_6() { return cPositionKeyword_6; }
		
		//position=[Lieu]
		public Assignment getPositionAssignment_7() { return cPositionAssignment_7; }
		
		//[Lieu]
		public CrossReference getPositionLieuCrossReference_7_0() { return cPositionLieuCrossReference_7_0; }
		
		//ID
		public RuleCall getPositionLieuIDTerminalRuleCall_7_0_1() { return cPositionLieuIDTerminalRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class SacElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Sac");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSacKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTailleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTailleINTTerminalRuleCall_1_0 = (RuleCall)cTailleAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSacElementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSacElementsObjetExplorateurCrossReference_3_0 = (CrossReference)cSacElementsAssignment_3.eContents().get(0);
		private final RuleCall cSacElementsObjetExplorateurIDTerminalRuleCall_3_0_1 = (RuleCall)cSacElementsObjetExplorateurCrossReference_3_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Sac:
		//	'sac'
		//	taille=INT
		//	'{'
		//	sacElements=[ObjetExplorateur]*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'sac' taille=INT '{' sacElements=[ObjetExplorateur]* '}'
		public Group getGroup() { return cGroup; }
		
		//'sac'
		public Keyword getSacKeyword_0() { return cSacKeyword_0; }
		
		//taille=INT
		public Assignment getTailleAssignment_1() { return cTailleAssignment_1; }
		
		//INT
		public RuleCall getTailleINTTerminalRuleCall_1_0() { return cTailleINTTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//sacElements=[ObjetExplorateur]*
		public Assignment getSacElementsAssignment_3() { return cSacElementsAssignment_3; }
		
		//[ObjetExplorateur]
		public CrossReference getSacElementsObjetExplorateurCrossReference_3_0() { return cSacElementsObjetExplorateurCrossReference_3_0; }
		
		//ID
		public RuleCall getSacElementsObjetExplorateurIDTerminalRuleCall_3_0_1() { return cSacElementsObjetExplorateurIDTerminalRuleCall_3_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class LieuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Lieu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTypeTypeLieuEnumRuleCall_0_0 = (RuleCall)cTypeAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Assignment cConditionDescriptionAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cConditionDescriptionConditionParserRuleCall_3_2_0 = (RuleCall)cConditionDescriptionAssignment_3_2.eContents().get(0);
		private final Assignment cPersonnesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cPersonnesPersonneCrossReference_4_0 = (CrossReference)cPersonnesAssignment_4.eContents().get(0);
		private final RuleCall cPersonnesPersonneIDTerminalRuleCall_4_0_1 = (RuleCall)cPersonnesPersonneCrossReference_4_0.eContents().get(1);
		private final Assignment cConnaissancesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cConnaissancesConnaissanceCrossReference_5_0 = (CrossReference)cConnaissancesAssignment_5.eContents().get(0);
		private final RuleCall cConnaissancesConnaissanceIDTerminalRuleCall_5_0_1 = (RuleCall)cConnaissancesConnaissanceCrossReference_5_0.eContents().get(1);
		private final Assignment cObjetsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cObjetsObjetLieuCrossReference_6_0 = (CrossReference)cObjetsAssignment_6.eContents().get(0);
		private final RuleCall cObjetsObjetLieuIDTerminalRuleCall_6_0_1 = (RuleCall)cObjetsObjetLieuCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cDepotOKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cDepotObjetAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cDepotObjetConditionParserRuleCall_7_1_0 = (RuleCall)cDepotObjetAssignment_7_1.eContents().get(0);
		private final Assignment cListeCheminsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cListeCheminsCheminCrossReference_8_0 = (CrossReference)cListeCheminsAssignment_8.eContents().get(0);
		private final RuleCall cListeCheminsCheminIDTerminalRuleCall_8_0_1 = (RuleCall)cListeCheminsCheminCrossReference_8_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Lieu:
		//	type=TypeLieu
		//	name=ID
		//	'{' ('description' description=STRING conditionDescription=Condition?)? //E39
		//	personnes=[Personne]*
		//	connaissances=[Connaissance]*
		//	objets=[ObjetLieu]* ('depotO' depotObjet=Condition)?
		//	listeChemins=[Chemin]*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//type=TypeLieu name=ID '{' ('description' description=STRING conditionDescription=Condition?)? //E39
		//personnes=[Personne]* connaissances=[Connaissance]* objets=[ObjetLieu]* ('depotO' depotObjet=Condition)?
		//listeChemins=[Chemin]* '}'
		public Group getGroup() { return cGroup; }
		
		//type=TypeLieu
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//TypeLieu
		public RuleCall getTypeTypeLieuEnumRuleCall_0_0() { return cTypeTypeLieuEnumRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('description' description=STRING conditionDescription=Condition?)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_1_0() { return cDescriptionSTRINGTerminalRuleCall_3_1_0; }
		
		//conditionDescription=Condition?
		public Assignment getConditionDescriptionAssignment_3_2() { return cConditionDescriptionAssignment_3_2; }
		
		//Condition
		public RuleCall getConditionDescriptionConditionParserRuleCall_3_2_0() { return cConditionDescriptionConditionParserRuleCall_3_2_0; }
		
		////E39
		//personnes=[Personne]*
		public Assignment getPersonnesAssignment_4() { return cPersonnesAssignment_4; }
		
		//[Personne]
		public CrossReference getPersonnesPersonneCrossReference_4_0() { return cPersonnesPersonneCrossReference_4_0; }
		
		//ID
		public RuleCall getPersonnesPersonneIDTerminalRuleCall_4_0_1() { return cPersonnesPersonneIDTerminalRuleCall_4_0_1; }
		
		//connaissances=[Connaissance]*
		public Assignment getConnaissancesAssignment_5() { return cConnaissancesAssignment_5; }
		
		//[Connaissance]
		public CrossReference getConnaissancesConnaissanceCrossReference_5_0() { return cConnaissancesConnaissanceCrossReference_5_0; }
		
		//ID
		public RuleCall getConnaissancesConnaissanceIDTerminalRuleCall_5_0_1() { return cConnaissancesConnaissanceIDTerminalRuleCall_5_0_1; }
		
		//objets=[ObjetLieu]*
		public Assignment getObjetsAssignment_6() { return cObjetsAssignment_6; }
		
		//[ObjetLieu]
		public CrossReference getObjetsObjetLieuCrossReference_6_0() { return cObjetsObjetLieuCrossReference_6_0; }
		
		//ID
		public RuleCall getObjetsObjetLieuIDTerminalRuleCall_6_0_1() { return cObjetsObjetLieuIDTerminalRuleCall_6_0_1; }
		
		//('depotO' depotObjet=Condition)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'depotO'
		public Keyword getDepotOKeyword_7_0() { return cDepotOKeyword_7_0; }
		
		//depotObjet=Condition
		public Assignment getDepotObjetAssignment_7_1() { return cDepotObjetAssignment_7_1; }
		
		//Condition
		public RuleCall getDepotObjetConditionParserRuleCall_7_1_0() { return cDepotObjetConditionParserRuleCall_7_1_0; }
		
		//listeChemins=[Chemin]*
		public Assignment getListeCheminsAssignment_8() { return cListeCheminsAssignment_8; }
		
		//[Chemin]
		public CrossReference getListeCheminsCheminCrossReference_8_0() { return cListeCheminsCheminCrossReference_8_0; }
		
		//ID
		public RuleCall getListeCheminsCheminIDTerminalRuleCall_8_0_1() { return cListeCheminsCheminIDTerminalRuleCall_8_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class PersonnesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Personnes");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonnesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cListePersonnesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cListePersonnesPersonneParserRuleCall_2_0 = (RuleCall)cListePersonnesAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Personnes:
		//	'personnes'
		//	'{'
		//	listePersonnes=Personne+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'personnes' '{' listePersonnes=Personne+ '}'
		public Group getGroup() { return cGroup; }
		
		//'personnes'
		public Keyword getPersonnesKeyword_0() { return cPersonnesKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//listePersonnes=Personne+
		public Assignment getListePersonnesAssignment_2() { return cListePersonnesAssignment_2; }
		
		//Personne
		public RuleCall getListePersonnesPersonneParserRuleCall_2_0() { return cListePersonnesPersonneParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class PersonneElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Personne");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cVisibleKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cVisibleAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cVisibleConditionCrossReference_2_1_0 = (CrossReference)cVisibleAssignment_2_1.eContents().get(0);
		private final RuleCall cVisibleConditionIDTerminalRuleCall_2_1_0_1 = (RuleCall)cVisibleConditionCrossReference_2_1_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cObligatoireKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cObligatoireAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cObligatoireConditionCrossReference_3_1_0 = (CrossReference)cObligatoireAssignment_3_1.eContents().get(0);
		private final RuleCall cObligatoireConditionIDTerminalRuleCall_3_1_0_1 = (RuleCall)cObligatoireConditionCrossReference_3_1_0.eContents().get(1);
		private final Assignment cPersonneElementsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPersonneElementsInteractionParserRuleCall_4_0 = (RuleCall)cPersonneElementsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Personne:
		//	name=ID
		//	'{' ('visible' visible=[Condition])? ('obligatoire' obligatoire=[Condition])?
		//	personneElements=Interaction
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '{' ('visible' visible=[Condition])? ('obligatoire' obligatoire=[Condition])? personneElements=Interaction '}'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('visible' visible=[Condition])?
		public Group getGroup_2() { return cGroup_2; }
		
		//'visible'
		public Keyword getVisibleKeyword_2_0() { return cVisibleKeyword_2_0; }
		
		//visible=[Condition]
		public Assignment getVisibleAssignment_2_1() { return cVisibleAssignment_2_1; }
		
		//[Condition]
		public CrossReference getVisibleConditionCrossReference_2_1_0() { return cVisibleConditionCrossReference_2_1_0; }
		
		//ID
		public RuleCall getVisibleConditionIDTerminalRuleCall_2_1_0_1() { return cVisibleConditionIDTerminalRuleCall_2_1_0_1; }
		
		//('obligatoire' obligatoire=[Condition])?
		public Group getGroup_3() { return cGroup_3; }
		
		//'obligatoire'
		public Keyword getObligatoireKeyword_3_0() { return cObligatoireKeyword_3_0; }
		
		//obligatoire=[Condition]
		public Assignment getObligatoireAssignment_3_1() { return cObligatoireAssignment_3_1; }
		
		//[Condition]
		public CrossReference getObligatoireConditionCrossReference_3_1_0() { return cObligatoireConditionCrossReference_3_1_0; }
		
		//ID
		public RuleCall getObligatoireConditionIDTerminalRuleCall_3_1_0_1() { return cObligatoireConditionIDTerminalRuleCall_3_1_0_1; }
		
		//personneElements=Interaction
		public Assignment getPersonneElementsAssignment_4() { return cPersonneElementsAssignment_4; }
		
		//Interaction
		public RuleCall getPersonneElementsInteractionParserRuleCall_4_0() { return cPersonneElementsInteractionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class InteractionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Interaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInteractionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTexteKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTexteAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTexteSTRINGTerminalRuleCall_4_0 = (RuleCall)cTexteAssignment_4.eContents().get(0);
		private final Assignment cInteractionElementsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cInteractionElementsChoixParserRuleCall_5_0 = (RuleCall)cInteractionElementsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Interaction:
		//	'interaction'
		//	name=ID
		//	'{'
		//	'texte' texte=STRING
		//	interactionElements=Choix* //E29
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'interaction' name=ID '{' 'texte' texte=STRING interactionElements=Choix* //E29
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'interaction'
		public Keyword getInteractionKeyword_0() { return cInteractionKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'texte'
		public Keyword getTexteKeyword_3() { return cTexteKeyword_3; }
		
		//texte=STRING
		public Assignment getTexteAssignment_4() { return cTexteAssignment_4; }
		
		//STRING
		public RuleCall getTexteSTRINGTerminalRuleCall_4_0() { return cTexteSTRINGTerminalRuleCall_4_0; }
		
		//interactionElements=Choix*
		public Assignment getInteractionElementsAssignment_5() { return cInteractionElementsAssignment_5; }
		
		//Choix
		public RuleCall getInteractionElementsChoixParserRuleCall_5_0() { return cInteractionElementsChoixParserRuleCall_5_0; }
		
		////E29
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ChoixElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Choix");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cChoixKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTexteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTexteSTRINGTerminalRuleCall_3_0 = (RuleCall)cTexteAssignment_3.eContents().get(0);
		private final Assignment cListeActionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cListeActionsActionParserRuleCall_4_0 = (RuleCall)cListeActionsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cChoixdebutKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Assignment cChoixdebutAssignment_5_1_0 = (Assignment)cGroup_5_1.eContents().get(0);
		private final RuleCall cChoixdebutSTRINGTerminalRuleCall_5_1_0_0 = (RuleCall)cChoixdebutAssignment_5_1_0.eContents().get(0);
		private final Assignment cConditonChoixDebutAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cConditonChoixDebutConditionParserRuleCall_5_1_1_0 = (RuleCall)cConditonChoixDebutAssignment_5_1_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cChoixfinKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Group cGroup_6_1 = (Group)cGroup_6.eContents().get(1);
		private final Assignment cChoixfinAssignment_6_1_0 = (Assignment)cGroup_6_1.eContents().get(0);
		private final RuleCall cChoixfinSTRINGTerminalRuleCall_6_1_0_0 = (RuleCall)cChoixfinAssignment_6_1_0.eContents().get(0);
		private final Assignment cConditionChoixFinAssignment_6_1_1 = (Assignment)cGroup_6_1.eContents().get(1);
		private final RuleCall cConditionChoixFinConditionParserRuleCall_6_1_1_0 = (RuleCall)cConditionChoixFinAssignment_6_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Choix:
		//	'choix'
		//	name=ID
		//	'{'
		//	texte=STRING
		//	listeActions=Action+ ('choixdebut' (choixdebut=STRING conditonChoixDebut=Condition)?)? ('choixfin' (choixfin=STRING
		//	conditionChoixFin=Condition)?)? //E34
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'choix' name=ID '{' texte=STRING listeActions=Action+ ('choixdebut' (choixdebut=STRING conditonChoixDebut=Condition)?)?
		//('choixfin' (choixfin=STRING conditionChoixFin=Condition)?)? //E34
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'choix'
		public Keyword getChoixKeyword_0() { return cChoixKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//texte=STRING
		public Assignment getTexteAssignment_3() { return cTexteAssignment_3; }
		
		//STRING
		public RuleCall getTexteSTRINGTerminalRuleCall_3_0() { return cTexteSTRINGTerminalRuleCall_3_0; }
		
		//listeActions=Action+
		public Assignment getListeActionsAssignment_4() { return cListeActionsAssignment_4; }
		
		//Action
		public RuleCall getListeActionsActionParserRuleCall_4_0() { return cListeActionsActionParserRuleCall_4_0; }
		
		//('choixdebut' (choixdebut=STRING conditonChoixDebut=Condition)?)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'choixdebut'
		public Keyword getChoixdebutKeyword_5_0() { return cChoixdebutKeyword_5_0; }
		
		//(choixdebut=STRING conditonChoixDebut=Condition)?
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//choixdebut=STRING
		public Assignment getChoixdebutAssignment_5_1_0() { return cChoixdebutAssignment_5_1_0; }
		
		//STRING
		public RuleCall getChoixdebutSTRINGTerminalRuleCall_5_1_0_0() { return cChoixdebutSTRINGTerminalRuleCall_5_1_0_0; }
		
		//conditonChoixDebut=Condition
		public Assignment getConditonChoixDebutAssignment_5_1_1() { return cConditonChoixDebutAssignment_5_1_1; }
		
		//Condition
		public RuleCall getConditonChoixDebutConditionParserRuleCall_5_1_1_0() { return cConditonChoixDebutConditionParserRuleCall_5_1_1_0; }
		
		//('choixfin' (choixfin=STRING conditionChoixFin=Condition)?)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'choixfin'
		public Keyword getChoixfinKeyword_6_0() { return cChoixfinKeyword_6_0; }
		
		//(choixfin=STRING conditionChoixFin=Condition)?
		public Group getGroup_6_1() { return cGroup_6_1; }
		
		//choixfin=STRING
		public Assignment getChoixfinAssignment_6_1_0() { return cChoixfinAssignment_6_1_0; }
		
		//STRING
		public RuleCall getChoixfinSTRINGTerminalRuleCall_6_1_0_0() { return cChoixfinSTRINGTerminalRuleCall_6_1_0_0; }
		
		//conditionChoixFin=Condition
		public Assignment getConditionChoixFinAssignment_6_1_1() { return cConditionChoixFinAssignment_6_1_1; }
		
		//Condition
		public RuleCall getConditionChoixFinConditionParserRuleCall_6_1_1_0() { return cConditionChoixFinConditionParserRuleCall_6_1_1_0; }
		
		////E34
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTexteAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTexteSTRINGTerminalRuleCall_2_0 = (RuleCall)cTexteAssignment_2.eContents().get(0);
		private final Assignment cConditionActionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConditionActionConditionParserRuleCall_3_0 = (RuleCall)cConditionActionAssignment_3.eContents().get(0);
		private final Assignment cListeChoixAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cListeChoixChoixCrossReference_4_0 = (CrossReference)cListeChoixAssignment_4.eContents().get(0);
		private final RuleCall cListeChoixChoixIDTerminalRuleCall_4_0_1 = (RuleCall)cListeChoixChoixCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDonneCKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cListeConnaissancesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cListeConnaissancesConnaissanceCrossReference_5_1_0 = (CrossReference)cListeConnaissancesAssignment_5_1.eContents().get(0);
		private final RuleCall cListeConnaissancesConnaissanceIDTerminalRuleCall_5_1_0_1 = (RuleCall)cListeConnaissancesConnaissanceCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDonneOKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cListeObjetsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cListeObjetsObjetLieuCrossReference_6_1_0 = (CrossReference)cListeObjetsAssignment_6_1.eContents().get(0);
		private final RuleCall cListeObjetsObjetLieuIDTerminalRuleCall_6_1_0_1 = (RuleCall)cListeObjetsObjetLieuCrossReference_6_1_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cAttributionCKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAttributionConnaissanceAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAttributionConnaissanceConditionParserRuleCall_7_1_0 = (RuleCall)cAttributionConnaissanceAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAttributionOKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cAttributionObjetAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cAttributionObjetConditionParserRuleCall_8_1_0 = (RuleCall)cAttributionObjetAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cConsommeOKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cListeObjetsConsommesAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cListeObjetsConsommesObjetExplorateurCrossReference_9_1_0 = (CrossReference)cListeObjetsConsommesAssignment_9_1.eContents().get(0);
		private final RuleCall cListeObjetsConsommesObjetExplorateurIDTerminalRuleCall_9_1_0_1 = (RuleCall)cListeObjetsConsommesObjetExplorateurCrossReference_9_1_0.eContents().get(1);
		private final Keyword cQuantiteOKeyword_9_2 = (Keyword)cGroup_9.eContents().get(2);
		private final Assignment cListeQuantiteAssignment_9_3 = (Assignment)cGroup_9.eContents().get(3);
		private final RuleCall cListeQuantiteINTTerminalRuleCall_9_3_0 = (RuleCall)cListeQuantiteAssignment_9_3.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cConsommationCKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cConsommationObjetAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cConsommationObjetConditionParserRuleCall_10_1_0 = (RuleCall)cConsommationObjetAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Action:
		//	'action'
		//	'{'
		//	texte=STRING
		//	conditionAction=Condition? //E32 et E35
		//	listeChoix=[Choix]* ('donneC' listeConnaissances=[Connaissance]*)? ('donneO' listeObjets=[ObjetLieu]*)? ('attributionC'
		//	attributionConnaissance=Condition)? ('attributionO' attributionObjet=Condition)? ('consommeO'
		//	listeObjetsConsommes=[ObjetExplorateur]* 'quantiteO' listeQuantite=INT*)? ('consommationC'
		//	consommationObjet=Condition)? //E38
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'action' '{' texte=STRING conditionAction=Condition? //E32 et E35
		//listeChoix=[Choix]* ('donneC' listeConnaissances=[Connaissance]*)? ('donneO' listeObjets=[ObjetLieu]*)? ('attributionC'
		//attributionConnaissance=Condition)? ('attributionO' attributionObjet=Condition)? ('consommeO'
		//listeObjetsConsommes=[ObjetExplorateur]* 'quantiteO' listeQuantite=INT*)? ('consommationC'
		//consommationObjet=Condition)? //E38
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'action'
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//texte=STRING
		public Assignment getTexteAssignment_2() { return cTexteAssignment_2; }
		
		//STRING
		public RuleCall getTexteSTRINGTerminalRuleCall_2_0() { return cTexteSTRINGTerminalRuleCall_2_0; }
		
		//conditionAction=Condition?
		public Assignment getConditionActionAssignment_3() { return cConditionActionAssignment_3; }
		
		//Condition
		public RuleCall getConditionActionConditionParserRuleCall_3_0() { return cConditionActionConditionParserRuleCall_3_0; }
		
		////E32 et E35
		//listeChoix=[Choix]*
		public Assignment getListeChoixAssignment_4() { return cListeChoixAssignment_4; }
		
		//[Choix]
		public CrossReference getListeChoixChoixCrossReference_4_0() { return cListeChoixChoixCrossReference_4_0; }
		
		//ID
		public RuleCall getListeChoixChoixIDTerminalRuleCall_4_0_1() { return cListeChoixChoixIDTerminalRuleCall_4_0_1; }
		
		//('donneC' listeConnaissances=[Connaissance]*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'donneC'
		public Keyword getDonneCKeyword_5_0() { return cDonneCKeyword_5_0; }
		
		//listeConnaissances=[Connaissance]*
		public Assignment getListeConnaissancesAssignment_5_1() { return cListeConnaissancesAssignment_5_1; }
		
		//[Connaissance]
		public CrossReference getListeConnaissancesConnaissanceCrossReference_5_1_0() { return cListeConnaissancesConnaissanceCrossReference_5_1_0; }
		
		//ID
		public RuleCall getListeConnaissancesConnaissanceIDTerminalRuleCall_5_1_0_1() { return cListeConnaissancesConnaissanceIDTerminalRuleCall_5_1_0_1; }
		
		//('donneO' listeObjets=[ObjetLieu]*)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'donneO'
		public Keyword getDonneOKeyword_6_0() { return cDonneOKeyword_6_0; }
		
		//listeObjets=[ObjetLieu]*
		public Assignment getListeObjetsAssignment_6_1() { return cListeObjetsAssignment_6_1; }
		
		//[ObjetLieu]
		public CrossReference getListeObjetsObjetLieuCrossReference_6_1_0() { return cListeObjetsObjetLieuCrossReference_6_1_0; }
		
		//ID
		public RuleCall getListeObjetsObjetLieuIDTerminalRuleCall_6_1_0_1() { return cListeObjetsObjetLieuIDTerminalRuleCall_6_1_0_1; }
		
		//('attributionC' attributionConnaissance=Condition)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'attributionC'
		public Keyword getAttributionCKeyword_7_0() { return cAttributionCKeyword_7_0; }
		
		//attributionConnaissance=Condition
		public Assignment getAttributionConnaissanceAssignment_7_1() { return cAttributionConnaissanceAssignment_7_1; }
		
		//Condition
		public RuleCall getAttributionConnaissanceConditionParserRuleCall_7_1_0() { return cAttributionConnaissanceConditionParserRuleCall_7_1_0; }
		
		//('attributionO' attributionObjet=Condition)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'attributionO'
		public Keyword getAttributionOKeyword_8_0() { return cAttributionOKeyword_8_0; }
		
		//attributionObjet=Condition
		public Assignment getAttributionObjetAssignment_8_1() { return cAttributionObjetAssignment_8_1; }
		
		//Condition
		public RuleCall getAttributionObjetConditionParserRuleCall_8_1_0() { return cAttributionObjetConditionParserRuleCall_8_1_0; }
		
		//('consommeO' listeObjetsConsommes=[ObjetExplorateur]* 'quantiteO' listeQuantite=INT*)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'consommeO'
		public Keyword getConsommeOKeyword_9_0() { return cConsommeOKeyword_9_0; }
		
		//listeObjetsConsommes=[ObjetExplorateur]*
		public Assignment getListeObjetsConsommesAssignment_9_1() { return cListeObjetsConsommesAssignment_9_1; }
		
		//[ObjetExplorateur]
		public CrossReference getListeObjetsConsommesObjetExplorateurCrossReference_9_1_0() { return cListeObjetsConsommesObjetExplorateurCrossReference_9_1_0; }
		
		//ID
		public RuleCall getListeObjetsConsommesObjetExplorateurIDTerminalRuleCall_9_1_0_1() { return cListeObjetsConsommesObjetExplorateurIDTerminalRuleCall_9_1_0_1; }
		
		//'quantiteO'
		public Keyword getQuantiteOKeyword_9_2() { return cQuantiteOKeyword_9_2; }
		
		//listeQuantite=INT*
		public Assignment getListeQuantiteAssignment_9_3() { return cListeQuantiteAssignment_9_3; }
		
		//INT
		public RuleCall getListeQuantiteINTTerminalRuleCall_9_3_0() { return cListeQuantiteINTTerminalRuleCall_9_3_0; }
		
		//('consommationC' consommationObjet=Condition)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'consommationC'
		public Keyword getConsommationCKeyword_10_0() { return cConsommationCKeyword_10_0; }
		
		//consommationObjet=Condition
		public Assignment getConsommationObjetAssignment_10_1() { return cConsommationObjetAssignment_10_1; }
		
		//Condition
		public RuleCall getConsommationObjetConditionParserRuleCall_10_1_0() { return cConsommationObjetConditionParserRuleCall_10_1_0; }
		
		////E38
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ObjetExplorateurElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.ObjetExplorateur");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTailleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTailleINTTerminalRuleCall_1_0 = (RuleCall)cTailleAssignment_1.eContents().get(0);
		private final Assignment cQuantiteAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cQuantiteINTTerminalRuleCall_2_0 = (RuleCall)cQuantiteAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Assignment cConditionDescriptionAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cConditionDescriptionConditionParserRuleCall_3_2_0 = (RuleCall)cConditionDescriptionAssignment_3_2.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTransformableKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTransformableAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTransformableConditionParserRuleCall_4_1_0 = (RuleCall)cTransformableAssignment_4_1.eContents().get(0);
		
		//ObjetExplorateur:
		//	name=ID
		//	taille=INT
		//	quantite=INT ('description' description=STRING conditionDescription=Condition?)? ('transformable'
		//	transformable=Condition?)? //E40
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID taille=INT quantite=INT ('description' description=STRING conditionDescription=Condition?)? ('transformable'
		//transformable=Condition?)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//taille=INT
		public Assignment getTailleAssignment_1() { return cTailleAssignment_1; }
		
		//INT
		public RuleCall getTailleINTTerminalRuleCall_1_0() { return cTailleINTTerminalRuleCall_1_0; }
		
		//quantite=INT
		public Assignment getQuantiteAssignment_2() { return cQuantiteAssignment_2; }
		
		//INT
		public RuleCall getQuantiteINTTerminalRuleCall_2_0() { return cQuantiteINTTerminalRuleCall_2_0; }
		
		//('description' description=STRING conditionDescription=Condition?)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'description'
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_1_0() { return cDescriptionSTRINGTerminalRuleCall_3_1_0; }
		
		//conditionDescription=Condition?
		public Assignment getConditionDescriptionAssignment_3_2() { return cConditionDescriptionAssignment_3_2; }
		
		//Condition
		public RuleCall getConditionDescriptionConditionParserRuleCall_3_2_0() { return cConditionDescriptionConditionParserRuleCall_3_2_0; }
		
		//('transformable' transformable=Condition?)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'transformable'
		public Keyword getTransformableKeyword_4_0() { return cTransformableKeyword_4_0; }
		
		//transformable=Condition?
		public Assignment getTransformableAssignment_4_1() { return cTransformableAssignment_4_1; }
		
		//Condition
		public RuleCall getTransformableConditionParserRuleCall_4_1_0() { return cTransformableConditionParserRuleCall_4_1_0; }
	}
	public class ObjetLieuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.ObjetLieu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTailleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTailleINTTerminalRuleCall_1_0 = (RuleCall)cTailleAssignment_1.eContents().get(0);
		private final Assignment cQuantiteAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cQuantiteINTTerminalRuleCall_2_0 = (RuleCall)cQuantiteAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTransmissionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cConditionTransmissionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cConditionTransmissionConditionParserRuleCall_3_1_0 = (RuleCall)cConditionTransmissionAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cConsommationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cConditionConsommationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cConditionConsommationConditionParserRuleCall_4_1_0 = (RuleCall)cConditionConsommationAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Assignment cConditionDescriptionAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cConditionDescriptionConditionParserRuleCall_5_2_0 = (RuleCall)cConditionDescriptionAssignment_5_2.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTransformableKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTransformableAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTransformableConditionParserRuleCall_6_1_0 = (RuleCall)cTransformableAssignment_6_1.eContents().get(0);
		
		//ObjetLieu:
		//	name=ID
		//	taille=INT
		//	quantite=INT ('transmission' conditionTransmission=Condition?)? ('consommation' conditionConsommation=Condition?)?
		//	('description' description=STRING conditionDescription=Condition?)? ('transformable' transformable=Condition?)? //E40
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID taille=INT quantite=INT ('transmission' conditionTransmission=Condition?)? ('consommation'
		//conditionConsommation=Condition?)? ('description' description=STRING conditionDescription=Condition?)? ('transformable'
		//transformable=Condition?)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//taille=INT
		public Assignment getTailleAssignment_1() { return cTailleAssignment_1; }
		
		//INT
		public RuleCall getTailleINTTerminalRuleCall_1_0() { return cTailleINTTerminalRuleCall_1_0; }
		
		//quantite=INT
		public Assignment getQuantiteAssignment_2() { return cQuantiteAssignment_2; }
		
		//INT
		public RuleCall getQuantiteINTTerminalRuleCall_2_0() { return cQuantiteINTTerminalRuleCall_2_0; }
		
		//('transmission' conditionTransmission=Condition?)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'transmission'
		public Keyword getTransmissionKeyword_3_0() { return cTransmissionKeyword_3_0; }
		
		//conditionTransmission=Condition?
		public Assignment getConditionTransmissionAssignment_3_1() { return cConditionTransmissionAssignment_3_1; }
		
		//Condition
		public RuleCall getConditionTransmissionConditionParserRuleCall_3_1_0() { return cConditionTransmissionConditionParserRuleCall_3_1_0; }
		
		//('consommation' conditionConsommation=Condition?)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'consommation'
		public Keyword getConsommationKeyword_4_0() { return cConsommationKeyword_4_0; }
		
		//conditionConsommation=Condition?
		public Assignment getConditionConsommationAssignment_4_1() { return cConditionConsommationAssignment_4_1; }
		
		//Condition
		public RuleCall getConditionConsommationConditionParserRuleCall_4_1_0() { return cConditionConsommationConditionParserRuleCall_4_1_0; }
		
		//('description' description=STRING conditionDescription=Condition?)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'description'
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_5_1_0() { return cDescriptionSTRINGTerminalRuleCall_5_1_0; }
		
		//conditionDescription=Condition?
		public Assignment getConditionDescriptionAssignment_5_2() { return cConditionDescriptionAssignment_5_2; }
		
		//Condition
		public RuleCall getConditionDescriptionConditionParserRuleCall_5_2_0() { return cConditionDescriptionConditionParserRuleCall_5_2_0; }
		
		//('transformable' transformable=Condition?)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'transformable'
		public Keyword getTransformableKeyword_6_0() { return cTransformableKeyword_6_0; }
		
		//transformable=Condition?
		public Assignment getTransformableAssignment_6_1() { return cTransformableAssignment_6_1; }
		
		//Condition
		public RuleCall getTransformableConditionParserRuleCall_6_1_0() { return cTransformableConditionParserRuleCall_6_1_0; }
	}
	public class ObjetsExplorateurElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.ObjetsExplorateur");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cObjetsEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cListeObjetsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cListeObjetsObjetExplorateurParserRuleCall_2_0 = (RuleCall)cListeObjetsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ObjetsExplorateur:
		//	'objetsE'
		//	'{'
		//	listeObjets=ObjetExplorateur*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'objetsE' '{' listeObjets=ObjetExplorateur* '}'
		public Group getGroup() { return cGroup; }
		
		//'objetsE'
		public Keyword getObjetsEKeyword_0() { return cObjetsEKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//listeObjets=ObjetExplorateur*
		public Assignment getListeObjetsAssignment_2() { return cListeObjetsAssignment_2; }
		
		//ObjetExplorateur
		public RuleCall getListeObjetsObjetExplorateurParserRuleCall_2_0() { return cListeObjetsObjetExplorateurParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ObjetsLieuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.ObjetsLieu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cObjetsLKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cListeObjetsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cListeObjetsObjetLieuParserRuleCall_2_0 = (RuleCall)cListeObjetsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ObjetsLieu:
		//	'objetsL'
		//	'{'
		//	listeObjets=ObjetLieu*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'objetsL' '{' listeObjets=ObjetLieu* '}'
		public Group getGroup() { return cGroup; }
		
		//'objetsL'
		public Keyword getObjetsLKeyword_0() { return cObjetsLKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//listeObjets=ObjetLieu*
		public Assignment getListeObjetsAssignment_2() { return cListeObjetsAssignment_2; }
		
		//ObjetLieu
		public RuleCall getListeObjetsObjetLieuParserRuleCall_2_0() { return cListeObjetsObjetLieuParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ConnaissancesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Connaissances");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnaissancesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cListeConnaissancesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cListeConnaissancesConnaissanceParserRuleCall_2_0 = (RuleCall)cListeConnaissancesAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Connaissances:
		//	'connaissances'
		//	'{'
		//	listeConnaissances+=Connaissance*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'connaissances' '{' listeConnaissances+=Connaissance* '}'
		public Group getGroup() { return cGroup; }
		
		//'connaissances'
		public Keyword getConnaissancesKeyword_0() { return cConnaissancesKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//listeConnaissances+=Connaissance*
		public Assignment getListeConnaissancesAssignment_2() { return cListeConnaissancesAssignment_2; }
		
		//Connaissance
		public RuleCall getListeConnaissancesConnaissanceParserRuleCall_2_0() { return cListeConnaissancesConnaissanceParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ConnaissanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Connaissance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cDescriptionKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDescriptionAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cDescriptionAssignment_1_1.eContents().get(0);
		private final Assignment cConditionConnaissanceAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cConditionConnaissanceConditionParserRuleCall_1_2_0 = (RuleCall)cConditionConnaissanceAssignment_1_2.eContents().get(0);
		
		//Connaissance:
		//	name=ID ('description' description=STRING conditionConnaissance=Condition?)? //E39
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID ('description' description=STRING conditionConnaissance=Condition?)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//('description' description=STRING conditionConnaissance=Condition?)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'description'
		public Keyword getDescriptionKeyword_1_0() { return cDescriptionKeyword_1_0; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_1_1() { return cDescriptionAssignment_1_1; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_1_1_0() { return cDescriptionSTRINGTerminalRuleCall_1_1_0; }
		
		//conditionConnaissance=Condition?
		public Assignment getConditionConnaissanceAssignment_1_2() { return cConditionConnaissanceAssignment_1_2; }
		
		//Condition
		public RuleCall getConditionConnaissanceConditionParserRuleCall_1_2_0() { return cConditionConnaissanceConditionParserRuleCall_1_2_0; }
	}
	public class ConditionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Conditions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConditionsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cListeConditionsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cListeConditionsConditionParserRuleCall_2_0 = (RuleCall)cListeConditionsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Conditions:
		//	'conditions'
		//	'{'
		//	listeConditions+=Condition*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'conditions' '{' listeConditions+=Condition* '}'
		public Group getGroup() { return cGroup; }
		
		//'conditions'
		public Keyword getConditionsKeyword_0() { return cConditionsKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//listeConditions+=Condition*
		public Assignment getListeConditionsAssignment_2() { return cListeConditionsAssignment_2; }
		
		//Condition
		public RuleCall getListeConditionsConditionParserRuleCall_2_0() { return cListeConditionsConditionParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cConditionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cConditionSTRINGTerminalRuleCall_1_0 = (RuleCall)cConditionAssignment_1.eContents().get(0);
		
		//Condition:
		//	name=ID condition=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID condition=STRING
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//condition=STRING
		public Assignment getConditionAssignment_1() { return cConditionAssignment_1; }
		
		//STRING
		public RuleCall getConditionSTRINGTerminalRuleCall_1_0() { return cConditionSTRINGTerminalRuleCall_1_0; }
	}
	public class CheminsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Chemins");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCheminsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cListeCheminsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cListeCheminsCheminParserRuleCall_2_0 = (RuleCall)cListeCheminsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Chemins:
		//	'chemins'
		//	'{'
		//	listeChemins=Chemin*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'chemins' '{' listeChemins=Chemin* '}'
		public Group getGroup() { return cGroup; }
		
		//'chemins'
		public Keyword getCheminsKeyword_0() { return cCheminsKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//listeChemins=Chemin*
		public Assignment getListeCheminsAssignment_2() { return cListeCheminsAssignment_2; }
		
		//Chemin
		public RuleCall getListeCheminsCheminParserRuleCall_2_0() { return cListeCheminsCheminParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class CheminElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.Chemin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDescriptionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Assignment cConditionDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cConditionDescriptionConditionParserRuleCall_4_0 = (RuleCall)cConditionDescriptionAssignment_4.eContents().get(0);
		private final Keyword cSourceKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSourceAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSourceLieuCrossReference_6_0 = (CrossReference)cSourceAssignment_6.eContents().get(0);
		private final RuleCall cSourceLieuIDTerminalRuleCall_6_0_1 = (RuleCall)cSourceLieuCrossReference_6_0.eContents().get(1);
		private final Keyword cDestinationKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDestinationAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cDestinationLieuCrossReference_8_0 = (CrossReference)cDestinationAssignment_8.eContents().get(0);
		private final RuleCall cDestinationLieuIDTerminalRuleCall_8_0_1 = (RuleCall)cDestinationLieuCrossReference_8_0.eContents().get(1);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cObligatoireKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cObligatoireAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cObligatoireConditionCrossReference_9_1_0 = (CrossReference)cObligatoireAssignment_9_1.eContents().get(0);
		private final RuleCall cObligatoireConditionIDTerminalRuleCall_9_1_0_1 = (RuleCall)cObligatoireConditionCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cVisibleKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cVisibleAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cVisibleConditionCrossReference_10_1_0 = (CrossReference)cVisibleAssignment_10_1.eContents().get(0);
		private final RuleCall cVisibleConditionIDTerminalRuleCall_10_1_0_1 = (RuleCall)cVisibleConditionCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cOuvertKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cOuvertAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cOuvertConditionCrossReference_11_1_0 = (CrossReference)cOuvertAssignment_11_1.eContents().get(0);
		private final RuleCall cOuvertConditionIDTerminalRuleCall_11_1_0_1 = (RuleCall)cOuvertConditionCrossReference_11_1_0.eContents().get(1);
		private final Assignment cListeConnaissancesAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final CrossReference cListeConnaissancesConnaissanceCrossReference_12_0 = (CrossReference)cListeConnaissancesAssignment_12.eContents().get(0);
		private final RuleCall cListeConnaissancesConnaissanceIDTerminalRuleCall_12_0_1 = (RuleCall)cListeConnaissancesConnaissanceCrossReference_12_0.eContents().get(1);
		private final Assignment cListeObjetsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final CrossReference cListeObjetsObjetsLieuCrossReference_13_0 = (CrossReference)cListeObjetsAssignment_13.eContents().get(0);
		private final RuleCall cListeObjetsObjetsLieuIDTerminalRuleCall_13_0_1 = (RuleCall)cListeObjetsObjetsLieuCrossReference_13_0.eContents().get(1);
		private final Assignment cListeObjetsConsommesAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final CrossReference cListeObjetsConsommesObjetsExplorateurCrossReference_14_0 = (CrossReference)cListeObjetsConsommesAssignment_14.eContents().get(0);
		private final RuleCall cListeObjetsConsommesObjetsExplorateurIDTerminalRuleCall_14_0_1 = (RuleCall)cListeObjetsConsommesObjetsExplorateurCrossReference_14_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Chemin:
		//	name=ID
		//	'{'
		//	'description' description=STRING conditionDescription=Condition? //E39
		//	'source' source=[Lieu]
		//	'destination' destination=[Lieu] ('obligatoire' obligatoire=[Condition])? ('visible' visible=[Condition])? ('ouvert'
		//	ouvert=[Condition])?
		//	listeConnaissances=[Connaissance]*
		//	listeObjets=[ObjetsLieu]*
		//	listeObjetsConsommes=[ObjetsExplorateur]*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '{' 'description' description=STRING conditionDescription=Condition? //E39
		//'source' source=[Lieu] 'destination' destination=[Lieu] ('obligatoire' obligatoire=[Condition])? ('visible'
		//visible=[Condition])? ('ouvert' ouvert=[Condition])? listeConnaissances=[Connaissance]* listeObjets=[ObjetsLieu]*
		//listeObjetsConsommes=[ObjetsExplorateur]* '}'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'description'
		public Keyword getDescriptionKeyword_2() { return cDescriptionKeyword_2; }
		
		//description=STRING
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }
		
		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_3_0() { return cDescriptionSTRINGTerminalRuleCall_3_0; }
		
		//conditionDescription=Condition?
		public Assignment getConditionDescriptionAssignment_4() { return cConditionDescriptionAssignment_4; }
		
		//Condition
		public RuleCall getConditionDescriptionConditionParserRuleCall_4_0() { return cConditionDescriptionConditionParserRuleCall_4_0; }
		
		////E39
		//'source'
		public Keyword getSourceKeyword_5() { return cSourceKeyword_5; }
		
		//source=[Lieu]
		public Assignment getSourceAssignment_6() { return cSourceAssignment_6; }
		
		//[Lieu]
		public CrossReference getSourceLieuCrossReference_6_0() { return cSourceLieuCrossReference_6_0; }
		
		//ID
		public RuleCall getSourceLieuIDTerminalRuleCall_6_0_1() { return cSourceLieuIDTerminalRuleCall_6_0_1; }
		
		//'destination'
		public Keyword getDestinationKeyword_7() { return cDestinationKeyword_7; }
		
		//destination=[Lieu]
		public Assignment getDestinationAssignment_8() { return cDestinationAssignment_8; }
		
		//[Lieu]
		public CrossReference getDestinationLieuCrossReference_8_0() { return cDestinationLieuCrossReference_8_0; }
		
		//ID
		public RuleCall getDestinationLieuIDTerminalRuleCall_8_0_1() { return cDestinationLieuIDTerminalRuleCall_8_0_1; }
		
		//('obligatoire' obligatoire=[Condition])?
		public Group getGroup_9() { return cGroup_9; }
		
		//'obligatoire'
		public Keyword getObligatoireKeyword_9_0() { return cObligatoireKeyword_9_0; }
		
		//obligatoire=[Condition]
		public Assignment getObligatoireAssignment_9_1() { return cObligatoireAssignment_9_1; }
		
		//[Condition]
		public CrossReference getObligatoireConditionCrossReference_9_1_0() { return cObligatoireConditionCrossReference_9_1_0; }
		
		//ID
		public RuleCall getObligatoireConditionIDTerminalRuleCall_9_1_0_1() { return cObligatoireConditionIDTerminalRuleCall_9_1_0_1; }
		
		//('visible' visible=[Condition])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'visible'
		public Keyword getVisibleKeyword_10_0() { return cVisibleKeyword_10_0; }
		
		//visible=[Condition]
		public Assignment getVisibleAssignment_10_1() { return cVisibleAssignment_10_1; }
		
		//[Condition]
		public CrossReference getVisibleConditionCrossReference_10_1_0() { return cVisibleConditionCrossReference_10_1_0; }
		
		//ID
		public RuleCall getVisibleConditionIDTerminalRuleCall_10_1_0_1() { return cVisibleConditionIDTerminalRuleCall_10_1_0_1; }
		
		//('ouvert' ouvert=[Condition])?
		public Group getGroup_11() { return cGroup_11; }
		
		//'ouvert'
		public Keyword getOuvertKeyword_11_0() { return cOuvertKeyword_11_0; }
		
		//ouvert=[Condition]
		public Assignment getOuvertAssignment_11_1() { return cOuvertAssignment_11_1; }
		
		//[Condition]
		public CrossReference getOuvertConditionCrossReference_11_1_0() { return cOuvertConditionCrossReference_11_1_0; }
		
		//ID
		public RuleCall getOuvertConditionIDTerminalRuleCall_11_1_0_1() { return cOuvertConditionIDTerminalRuleCall_11_1_0_1; }
		
		//listeConnaissances=[Connaissance]*
		public Assignment getListeConnaissancesAssignment_12() { return cListeConnaissancesAssignment_12; }
		
		//[Connaissance]
		public CrossReference getListeConnaissancesConnaissanceCrossReference_12_0() { return cListeConnaissancesConnaissanceCrossReference_12_0; }
		
		//ID
		public RuleCall getListeConnaissancesConnaissanceIDTerminalRuleCall_12_0_1() { return cListeConnaissancesConnaissanceIDTerminalRuleCall_12_0_1; }
		
		//listeObjets=[ObjetsLieu]*
		public Assignment getListeObjetsAssignment_13() { return cListeObjetsAssignment_13; }
		
		//[ObjetsLieu]
		public CrossReference getListeObjetsObjetsLieuCrossReference_13_0() { return cListeObjetsObjetsLieuCrossReference_13_0; }
		
		//ID
		public RuleCall getListeObjetsObjetsLieuIDTerminalRuleCall_13_0_1() { return cListeObjetsObjetsLieuIDTerminalRuleCall_13_0_1; }
		
		//listeObjetsConsommes=[ObjetsExplorateur]*
		public Assignment getListeObjetsConsommesAssignment_14() { return cListeObjetsConsommesAssignment_14; }
		
		//[ObjetsExplorateur]
		public CrossReference getListeObjetsConsommesObjetsExplorateurCrossReference_14_0() { return cListeObjetsConsommesObjetsExplorateurCrossReference_14_0; }
		
		//ID
		public RuleCall getListeObjetsConsommesObjetsExplorateurIDTerminalRuleCall_14_0_1() { return cListeObjetsConsommesObjetsExplorateurIDTerminalRuleCall_14_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	
	public class TypeLieuElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.TypeLieu");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLieuDebutEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLieuDebutDebutKeyword_0_0 = (Keyword)cLieuDebutEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLieuFinEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLieuFinFinKeyword_1_0 = (Keyword)cLieuFinEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLieuIntermediaireEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLieuIntermediaireIntermediaireKeyword_2_0 = (Keyword)cLieuIntermediaireEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum TypeLieu:
		//	LieuDebut='debut'
		//	| LieuFin='fin'
		//	| LieuIntermediaire='intermediaire';
		public EnumRule getRule() { return rule; }
		
		//LieuDebut='debut' | LieuFin='fin' | LieuIntermediaire='intermediaire'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//LieuDebut='debut'
		public EnumLiteralDeclaration getLieuDebutEnumLiteralDeclaration_0() { return cLieuDebutEnumLiteralDeclaration_0; }
		
		//'debut'
		public Keyword getLieuDebutDebutKeyword_0_0() { return cLieuDebutDebutKeyword_0_0; }
		
		//LieuFin='fin'
		public EnumLiteralDeclaration getLieuFinEnumLiteralDeclaration_1() { return cLieuFinEnumLiteralDeclaration_1; }
		
		//'fin'
		public Keyword getLieuFinFinKeyword_1_0() { return cLieuFinFinKeyword_1_0; }
		
		//LieuIntermediaire='intermediaire'
		public EnumLiteralDeclaration getLieuIntermediaireEnumLiteralDeclaration_2() { return cLieuIntermediaireEnumLiteralDeclaration_2; }
		
		//'intermediaire'
		public Keyword getLieuIntermediaireIntermediaireKeyword_2_0() { return cLieuIntermediaireIntermediaireKeyword_2_0; }
	}
	
	private final GameElements pGame;
	private final TerminalRule tBOOL;
	private final TerminalRule tCOND;
	private final TerritoireElementElements pTerritoireElement;
	private final ExplorateurElements pExplorateur;
	private final SacElements pSac;
	private final TypeLieuElements eTypeLieu;
	private final LieuElements pLieu;
	private final PersonnesElements pPersonnes;
	private final PersonneElements pPersonne;
	private final InteractionElements pInteraction;
	private final ChoixElements pChoix;
	private final ActionElements pAction;
	private final ObjetExplorateurElements pObjetExplorateur;
	private final ObjetLieuElements pObjetLieu;
	private final ObjetsExplorateurElements pObjetsExplorateur;
	private final ObjetsLieuElements pObjetsLieu;
	private final ConnaissancesElements pConnaissances;
	private final ConnaissanceElements pConnaissance;
	private final ConditionsElements pConditions;
	private final ConditionElements pCondition;
	private final CheminsElements pChemins;
	private final CheminElements pChemin;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GameGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGame = new GameElements();
		this.tBOOL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.BOOL");
		this.tCOND = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "fr.n7.Game.COND");
		this.pTerritoireElement = new TerritoireElementElements();
		this.pExplorateur = new ExplorateurElements();
		this.pSac = new SacElements();
		this.eTypeLieu = new TypeLieuElements();
		this.pLieu = new LieuElements();
		this.pPersonnes = new PersonnesElements();
		this.pPersonne = new PersonneElements();
		this.pInteraction = new InteractionElements();
		this.pChoix = new ChoixElements();
		this.pAction = new ActionElements();
		this.pObjetExplorateur = new ObjetExplorateurElements();
		this.pObjetLieu = new ObjetLieuElements();
		this.pObjetsExplorateur = new ObjetsExplorateurElements();
		this.pObjetsLieu = new ObjetsLieuElements();
		this.pConnaissances = new ConnaissancesElements();
		this.pConnaissance = new ConnaissanceElements();
		this.pConditions = new ConditionsElements();
		this.pCondition = new ConditionElements();
		this.pChemins = new CheminsElements();
		this.pChemin = new CheminElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.n7.Game".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Game:
	//	'territoire'
	//	name=ID
	//	'{'
	//	territoireElements+=territoireElement+
	//	'}';
	public GameElements getGameAccess() {
		return pGame;
	}
	
	public ParserRule getGameRule() {
		return getGameAccess().getRule();
	}
	
	//terminal BOOL returns ecore::EBoolean:
	//	'true' | 'false';
	public TerminalRule getBOOLRule() {
		return tBOOL;
	}
	
	//terminal COND returns ecore::EBoolean:
	//	STRING;
	public TerminalRule getCONDRule() {
		return tCOND;
	}
	
	//territoireElement:
	//	Explorateur | Lieu | ObjetsExplorateur | ObjetsLieu | Connaissances | Personnes | Chemins | Conditions;
	public TerritoireElementElements getTerritoireElementAccess() {
		return pTerritoireElement;
	}
	
	public ParserRule getTerritoireElementRule() {
		return getTerritoireElementAccess().getRule();
	}
	
	//Explorateur:
	//	'explorateur'
	//	name=ID
	//	'{'
	//	sac=Sac
	//	'connaissances' connaissances=[Connaissance]*
	//	'position' position=[Lieu]
	//	'}';
	public ExplorateurElements getExplorateurAccess() {
		return pExplorateur;
	}
	
	public ParserRule getExplorateurRule() {
		return getExplorateurAccess().getRule();
	}
	
	//Sac:
	//	'sac'
	//	taille=INT
	//	'{'
	//	sacElements=[ObjetExplorateur]*
	//	'}';
	public SacElements getSacAccess() {
		return pSac;
	}
	
	public ParserRule getSacRule() {
		return getSacAccess().getRule();
	}
	
	//enum TypeLieu:
	//	LieuDebut='debut'
	//	| LieuFin='fin'
	//	| LieuIntermediaire='intermediaire';
	public TypeLieuElements getTypeLieuAccess() {
		return eTypeLieu;
	}
	
	public EnumRule getTypeLieuRule() {
		return getTypeLieuAccess().getRule();
	}
	
	//Lieu:
	//	type=TypeLieu
	//	name=ID
	//	'{' ('description' description=STRING conditionDescription=Condition?)? //E39
	//	personnes=[Personne]*
	//	connaissances=[Connaissance]*
	//	objets=[ObjetLieu]* ('depotO' depotObjet=Condition)?
	//	listeChemins=[Chemin]*
	//	'}';
	public LieuElements getLieuAccess() {
		return pLieu;
	}
	
	public ParserRule getLieuRule() {
		return getLieuAccess().getRule();
	}
	
	//Personnes:
	//	'personnes'
	//	'{'
	//	listePersonnes=Personne+
	//	'}';
	public PersonnesElements getPersonnesAccess() {
		return pPersonnes;
	}
	
	public ParserRule getPersonnesRule() {
		return getPersonnesAccess().getRule();
	}
	
	//Personne:
	//	name=ID
	//	'{' ('visible' visible=[Condition])? ('obligatoire' obligatoire=[Condition])?
	//	personneElements=Interaction
	//	'}';
	public PersonneElements getPersonneAccess() {
		return pPersonne;
	}
	
	public ParserRule getPersonneRule() {
		return getPersonneAccess().getRule();
	}
	
	//Interaction:
	//	'interaction'
	//	name=ID
	//	'{'
	//	'texte' texte=STRING
	//	interactionElements=Choix* //E29
	//	'}';
	public InteractionElements getInteractionAccess() {
		return pInteraction;
	}
	
	public ParserRule getInteractionRule() {
		return getInteractionAccess().getRule();
	}
	
	//Choix:
	//	'choix'
	//	name=ID
	//	'{'
	//	texte=STRING
	//	listeActions=Action+ ('choixdebut' (choixdebut=STRING conditonChoixDebut=Condition)?)? ('choixfin' (choixfin=STRING
	//	conditionChoixFin=Condition)?)? //E34
	//	'}';
	public ChoixElements getChoixAccess() {
		return pChoix;
	}
	
	public ParserRule getChoixRule() {
		return getChoixAccess().getRule();
	}
	
	//Action:
	//	'action'
	//	'{'
	//	texte=STRING
	//	conditionAction=Condition? //E32 et E35
	//	listeChoix=[Choix]* ('donneC' listeConnaissances=[Connaissance]*)? ('donneO' listeObjets=[ObjetLieu]*)? ('attributionC'
	//	attributionConnaissance=Condition)? ('attributionO' attributionObjet=Condition)? ('consommeO'
	//	listeObjetsConsommes=[ObjetExplorateur]* 'quantiteO' listeQuantite=INT*)? ('consommationC'
	//	consommationObjet=Condition)? //E38
	//	'}';
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//ObjetExplorateur:
	//	name=ID
	//	taille=INT
	//	quantite=INT ('description' description=STRING conditionDescription=Condition?)? ('transformable'
	//	transformable=Condition?)? //E40
	//;
	public ObjetExplorateurElements getObjetExplorateurAccess() {
		return pObjetExplorateur;
	}
	
	public ParserRule getObjetExplorateurRule() {
		return getObjetExplorateurAccess().getRule();
	}
	
	//ObjetLieu:
	//	name=ID
	//	taille=INT
	//	quantite=INT ('transmission' conditionTransmission=Condition?)? ('consommation' conditionConsommation=Condition?)?
	//	('description' description=STRING conditionDescription=Condition?)? ('transformable' transformable=Condition?)? //E40
	//;
	public ObjetLieuElements getObjetLieuAccess() {
		return pObjetLieu;
	}
	
	public ParserRule getObjetLieuRule() {
		return getObjetLieuAccess().getRule();
	}
	
	//ObjetsExplorateur:
	//	'objetsE'
	//	'{'
	//	listeObjets=ObjetExplorateur*
	//	'}';
	public ObjetsExplorateurElements getObjetsExplorateurAccess() {
		return pObjetsExplorateur;
	}
	
	public ParserRule getObjetsExplorateurRule() {
		return getObjetsExplorateurAccess().getRule();
	}
	
	//ObjetsLieu:
	//	'objetsL'
	//	'{'
	//	listeObjets=ObjetLieu*
	//	'}';
	public ObjetsLieuElements getObjetsLieuAccess() {
		return pObjetsLieu;
	}
	
	public ParserRule getObjetsLieuRule() {
		return getObjetsLieuAccess().getRule();
	}
	
	//Connaissances:
	//	'connaissances'
	//	'{'
	//	listeConnaissances+=Connaissance*
	//	'}';
	public ConnaissancesElements getConnaissancesAccess() {
		return pConnaissances;
	}
	
	public ParserRule getConnaissancesRule() {
		return getConnaissancesAccess().getRule();
	}
	
	//Connaissance:
	//	name=ID ('description' description=STRING conditionConnaissance=Condition?)? //E39
	//;
	public ConnaissanceElements getConnaissanceAccess() {
		return pConnaissance;
	}
	
	public ParserRule getConnaissanceRule() {
		return getConnaissanceAccess().getRule();
	}
	
	//Conditions:
	//	'conditions'
	//	'{'
	//	listeConditions+=Condition*
	//	'}';
	public ConditionsElements getConditionsAccess() {
		return pConditions;
	}
	
	public ParserRule getConditionsRule() {
		return getConditionsAccess().getRule();
	}
	
	//Condition:
	//	name=ID condition=STRING;
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//Chemins:
	//	'chemins'
	//	'{'
	//	listeChemins=Chemin*
	//	'}';
	public CheminsElements getCheminsAccess() {
		return pChemins;
	}
	
	public ParserRule getCheminsRule() {
		return getCheminsAccess().getRule();
	}
	
	//Chemin:
	//	name=ID
	//	'{'
	//	'description' description=STRING conditionDescription=Condition? //E39
	//	'source' source=[Lieu]
	//	'destination' destination=[Lieu] ('obligatoire' obligatoire=[Condition])? ('visible' visible=[Condition])? ('ouvert'
	//	ouvert=[Condition])?
	//	listeConnaissances=[Connaissance]*
	//	listeObjets=[ObjetsLieu]*
	//	listeObjetsConsommes=[ObjetsExplorateur]*
	//	'}';
	public CheminElements getCheminAccess() {
		return pChemin;
	}
	
	public ParserRule getCheminRule() {
		return getCheminAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
